// Single source for docs/sublanding-roadmap.md and the visual board.
// Source: "Rankbox - Sublanding Pages.pdf" (Semrush US data, supplied 2026-10-02).
// q rows: [query, volume/mo, KD, CPC]. null = the PDF gave no figure.

export const UPDATED = "2026-10-02";

// Routes that are live. Add a route here when its page ships, then regenerate.
export const DONE = ["/solutions", "/solutions/autonomous-geo"];

// No templates. Every page is designed and built from scratch by its own agent,
// in its own directory. These describe how, and what may be shared.
export const WORKFLOW = {
  agent: ".claude/agents/sublanding-page-designer.md",
  steps: [
    ["One page, one agent", "Each page is built by its own sublanding-page-designer agent: a senior UI/UX designer and front-end engineer who owns that page alone, from research to the last pixel."],
    ["One page, one directory", "Everything visible on the page lives in src/sublanding/<section>/<slug>/: BRIEF.md (concept, audience, sources, section plan, how it differs from its neighbours), content.ts (every word, the meta and the FAQ), Page.tsx and the page's own section components, and its own test. The route file in src/routes is a thin wrapper."],
    ["Research before design", "The agent reads the page's roadmap entry, checks every competitor or industry fact on its primary source that day, and writes BRIEF.md before any code."],
    ["Designed from a blank page", "Own layout, own focal visual, own section order and own copy. The concept in the roadmap is the starting idea; the agent may sharpen it but may not borrow another page's design."],
    ["Checked against every other page", "sublanding.test.ts fails on more than 8% shared 8-word phrasing between any two pages, any shared H2 or FAQ question, a repeated title, description or H1, or an import from another page's directory."],
    ["Reviewed, then wired", "The main session reviews each page in the browser at desktop and phone width, then wires it into the shared files (registry, link graph, sitemap, llms.txt) and ticks it off."],
  ],
  shared: [
    "Brand: colour tokens, fonts, the blue-CTA rule, Navbar and Footer",
    "shadcn/ui primitives (button, input, tabs) and lucide icons",
    "Internal links: <ExploreMore>, driven by the link graph",
    "Facts: prices and trial length (pricing.ts), SHIPPED and addonLive",
    "Engines: real server checks such as checkAiReadiness and the robots parser",
    "Invisible plumbing: the head and JSON-LD helper, the registry, the tests",
  ],
  bespoke: [
    "Layout, composition and section order",
    "The focal visual and every interactive piece",
    "All copy: headings, body, FAQ, meta title and description",
    "Research: prompts, schema types, rules and sources",
    "Illustrations, scenes and mock UI",
  ],
};

export const PHASES = [
  {
    n: 0,
    title: "Foundations, hub + pilot",
    why: "Set up the per-page system once: the agent, the directory contract and the tests that keep 100 pages from looking or reading alike. Then two pages prove it.",
    needs: "Your call on /features/citation-tracking (the two FAQ overclaims are fixed in this phase).",
    work: [
      "The page agent: .claude/agents/sublanding-page-designer.md, a senior UI/UX designer and engineer that builds one page in one directory.",
      "The directory contract: src/sublanding/README.md. Each page owns src/sublanding/<section>/<slug>/ with BRIEF.md, content.ts, Page.tsx, its own sections and its own test.",
      "Invisible plumbing only, in src/sublanding/_shared/: the head and JSON-LD helper for any route (SoftwareApplication with offers from PLAN and no aggregateRating, FAQPage, BreadcrumbList), and a facts module that reads price, trial and SHIPPED from their sources.",
      "src/sublanding/sublanding.test.ts: every page has its directory, brief, content and route; imports stay inside the whitelist; no claim beyond SHIPPED / addonLive; no \"Rankvolt\", \"2-day\" or \"no credit card\"; no typed prices; and the cross-page uniqueness checks.",
      "Pre-flight fixes: the pricing FAQ no longer says citation tracking works in the trial, and the Prompt Kit FAQ no longer says Rankbox tracks prompts daily. /features/citation-tracking still describes an unshipped feature: your call.",
      "The /solutions hub (its own agent and directory) replaces today's 301 to /features.",
      "Pilot page: /solutions/autonomous-geo, built by its own agent.",
    ],
  },
  { n: 1, title: "Free scans", why: "Highest-converting format in the PDF, and every check can run for real today.", needs: "Nothing extra." },
  { n: 2, title: "Category money pages", why: "Large clusters with $15–20 CPCs that describe exactly what Rankbox does.", needs: "Dated agency price research for the cost calculator." },
  { n: 3, title: "Alternatives: content & keyword tools", why: "Moz alone is 1,600/mo at $28.75. These buyers already pay for a tool.", needs: "Vendor pages checked the day of writing." },
  { n: 4, title: "Alternatives: SEO suites", why: "$13–16 CPCs from teams on enterprise and mid-market suites.", needs: "Vendor pages checked the day of writing." },
  { n: 5, title: "Alternatives: audit & reporting tools", why: "Pairs with Phase 1: the free scans are the switching hook.", needs: "Vendor pages checked the day of writing." },
  { n: 6, title: "Alternatives: GEO trackers", why: "Buyers who already understand GEO. Stronger once tracking ships, workable now with the build-not-track argument.", needs: "Vendor pages checked the day of writing. Reads better after the tracking build." },
  { n: 7, title: "Platforms", why: "Magento + BigCommerce is a 6,500/mo cluster; headless CMS fits the API exactly.", needs: "Nothing extra. Shopify and Webflow copy follows addonLive." },
  { n: 8, title: "Engines & entities", why: "Engine and knowledge-graph searchers with real free checks to offer.", needs: "Nothing extra." },
  { n: 9, title: "SaaS & developers", why: "Closest to Rankbox's buyers today. The dev page can use the real llms.txt study data.", needs: "Nothing extra." },
  { n: 10, title: "Commerce & AI agents", why: "1,600 + 1,300 + 880/mo around ChatGPT shopping and checkout.", needs: "OpenAI's current shopping and checkout docs checked the day of writing; these change monthly." },
  { n: 11, title: "Legal", why: "$73–92 CPCs. Bar advertising rules make each page genuinely different.", needs: "Nothing extra. Pages give general information, not legal advice." },
  { n: 12, title: "Home services", why: "HVAC alone is 5,300/mo with a $63 CPC; self-storage is KD 2.", needs: "Nothing extra." },
  { n: 13, title: "Healthcare practices", why: "$21–43 CPCs with low KD; HIPAA and board rules give each page real substance.", needs: "Nothing extra." },
  { n: 14, title: "Behavioral health & life sciences", why: "Rehab is the PDF's $50 CPC; FDA and LegitScript rules shape what can be said.", needs: "Nothing extra. Highest-care copy on the site." },
  { n: 15, title: "Finance", why: "Private equity is KD 1 at $56.90; SEC, FINRA and Reg D rules are the differentiator.", needs: "Nothing extra." },
  { n: 16, title: "Multi-location & local", why: "Franchise and automotive are 4,300 and 5,500/mo clusters.", needs: "A decision on how per-site pricing reads to 300-location brands." },
  { n: 17, title: "B2B services & education", why: "Manufacturing is a $33 CPC with no software ranking; MSP's top result says SEO isn't worth it.", needs: "Nothing extra." },
  { n: 18, title: "Real estate & built environment", why: "Architect SEO is 1,600/mo at KD 1.", needs: "Nothing extra. Fair Housing rules apply." },
  { n: 19, title: "Alternatives: off-category", why: "$25–34 CPCs, but these tools do a different job. Lowest product fit in the PDF.", needs: "Your call on whether to build them." },
  { n: 20, title: "Refresh the live alternatives", why: "Frase, Surfer and Jasper pages exist. Add the PDF's angles and re-check prices (due quarterly).", needs: "Nothing extra." },
  { n: 21, title: "Tracking I: engine trackers", why: "The PDF's Tier 1 \"instant wins\" (KD 0). They need a tracker to exist first.", needs: "Citation tracking shipped: API keys and a monthly budget for each engine, plus a scheduler." },
  { n: 22, title: "Tracking II: citations, prompts & AI Overviews", why: "AI Overview tracking alone is a 3,500/mo cluster.", needs: "Phase 21's engine, plus a SERP API key for AI Overviews." },
  { n: 23, title: "Brand & AI search console", why: "1,600/mo × 3 at $14–19 CPC: the biggest cluster in the PDF.", needs: "Phase 21's engine." },
];

const P = (o) => o;

export const PAGES = [
  /* ---------------- Phase 0 pilot ---------------- */
  P({
    phase: 0, route: "/solutions", name: "Solutions hub", dir: "src/sublanding/solutions/_index/", status: "new", extra: true,
    concept: "A switchboard: every solution page as one searchable index, grouped by the job, the platform or the industry, that grows as each phase ships.",
    q: [],
    hook: "Find the page for your job, your platform or your industry.",
    build: "Not in the PDF. Needed now that three /solutions pages exist; replaces the 301 to /features. Reads the light SOLUTIONS index, so new pages appear without editing the hub.",
    truth: "Lists only live pages.",
    overlap: ["/features", "/use-cases"],
  }),
  P({
    phase: 0, route: "/solutions/autonomous-geo", name: "Autonomous GEO", dir: "src/sublanding/solutions/autonomous-geo/", status: "new",
    concept: "\"Two Mondays\": the same 30 days drawn as an audit to-do list on one side and as published answers on the other. One switch flips the page between homework and done.",
    q: [["ai search optimization tools", 1600, null, 17.53], ["llm seo tool", 1000, null, 9.38], ["ai visibility tracker", 880, null, 12.42], ["ai rank tracking", 590, null, 11.73]],
    hook: "Legacy SEO tools give you homework. Rankbox does the work: it finds the questions engines answer without you and publishes the answers.",
    build: "Concept module: an \"Audit vs autopilot\" toggle. One side is a 50-row audit checklist, the other is the same 30 days as published articles. Then a fair matrix against suites (Ahrefs, Semrush, Surfer) and the loop.",
    truth: "The tracker queries in this cluster (ai visibility tracker, ai rank tracking) must not be answered with a tracking claim. \"Publishes to your CMS\" means the API today; the Shopify and Webflow apps are in review.",
    overlap: ["/solutions/aeo-tools", "/solutions/ai-search-visibility", "/features/auto-publishing", "blog: ai-search-optimization-tools (peer session)"],
  }),

  /* ---------------- Phase 1 free scans ---------------- */
  P({
    phase: 1, route: "/tools/ai-search-audit", name: "AI Search Audit", dir: "src/sublanding/tools/ai-search-audit/", status: "new",
    concept: "Report first: the page opens on a finished audit of rankbox.xyz (a real run), laid out like a document, with the URL bar as its header. Your URL redraws the document.",
    q: [["ai search audit", 390, 16, 12.32]],
    hook: "Free AI search visibility audit: one input bar, an instant citation-readiness report.",
    build: "Site-level audit: every AI bot's access in robots.txt, llms.txt, sitemap, schema on the home page, then five sampled pages scored with the citation-readiness rules. Uses checkAiReadiness plus the CitationReadinessChecker rules on fetched HTML.",
    truth: "It measures readiness to be cited, not citations. Say so in the hero subline.",
    overlap: ["/tools/ai-search-readiness-check (the quick one-URL sibling)", "blog: aeo-audit", "blog: ai-seo-checklist-pre-publish-audit"],
  }),
  P({
    phase: 1, route: "/tools/aeo-checker", name: "AEO Checker", dir: "src/sublanding/tools/aeo-checker/", status: "new",
    concept: "An X-ray of one page: your URL loads as a wireframe of its own headings, each lit green, amber or red for how answer-ready the passage under it is.",
    q: [["aeo checker", 390, 10, 6.1]],
    hook: "One-click URL check for question headings, answer-ready schema and entity clarity.",
    build: "Page-level lens: question-style headings, an answer in the first 40–60 words under each, FAQ/HowTo/Article schema, Organization with sameAs, passage length. Fetches the URL; the existing checker only takes pasted text.",
    truth: "Nothing to correct.",
    overlap: ["/tools/ai-citation-readiness-checker (paste version)", "/solutions/aeo-tools hero scan"],
  }),
  P({
    phase: 1, route: "/solutions/geo-audit", name: "GEO Audit", dir: "src/sublanding/solutions/geo-audit/", status: "new",
    concept: "A scoreboard: five engine columns side by side, each with its crawler's name, an access verdict and a read verdict. The page is the scoreboard.",
    q: [["geo audit", 210, 15, 6.68]],
    hook: "A GEO scorecard across ChatGPT, Perplexity, Claude, Gemini and Copilot.",
    build: "One column per engine scoring what that engine needs to reach and read you: OAI-SearchBot and GPTBot, PerplexityBot, ClaudeBot and Claude-SearchBot, Google-Extended, Bingbot. Each column ends with that engine's Prompt Kit prompts to check presence by hand.",
    truth: "The PDF says it benchmarks brand presence. Presence needs tracking, so the v1 scorecard is access and readiness; it upgrades to live presence when tracking ships.",
    overlap: ["/ai-seo/* engine guides", "/tools/ai-visibility-prompt-generator"],
  }),
  P({
    phase: 1, route: "/tools/aeo-audit", name: "AEO Audit", dir: "src/sublanding/tools/aeo-audit/", status: "new",
    concept: "A structured-data inspector: your JSON-LD as a tree on the left, the entity card an engine would build from it on the right, gaps marked.",
    q: [["aeo audit", 50, 9, 7.36]],
    hook: "A technical answer engine optimization health check: structured data and the entity graph.",
    build: "Schema lens: JSON-LD parse errors, @types found, Organization / WebSite / sameAs completeness, and a Wikidata lookup for the brand (free public API).",
    truth: "Nothing to correct.",
    overlap: ["blog: aeo-audit (the method; the tool links to it and back)", "/tools/schema-generator"],
  }),
  P({
    phase: 1, route: "/solutions/ai-traffic-analytics", name: "AI Traffic Analytics", dir: "src/sublanding/solutions/ai-traffic-analytics/", status: "new",
    concept: "A GA4-style channel table where an \"AI assistants\" row appears as you tick engines, and the regex builds live underneath, ready to copy.",
    q: [["ai traffic analytics", 480, null, null], ["track chatgpt traffic", 320, null, null], ["chatgpt source tracking tools", 260, null, null], ["track gemini traffic", 260, null, null], ["ai traffic analysis", 210, null, 35.83]],
    hook: "Stop letting GA4 hide your AI search traffic.",
    build: "Free builder: pick engines, get the GA4 channel-group regex and the steps, check it against sample referrers. Then how Rankbox grows that line.",
    truth: "\"Reveal the exact ChatGPT prompts\" is impossible for any tool; cut it. GA4 has shipped an AI assistant channel since 2026-05-13, so the page explains what it covers and what it misses instead of saying GA4 hides everything.",
    overlap: ["blog: how-to-measure-ai-referral-traffic-in-ga4", "blog: how-to-track-ai-referral-traffic-in-ga4", "blog: chatgpt-traffic-analysis"],
  }),

  /* ---------------- Phase 2 category ---------------- */
  P({
    phase: 2, route: "/solutions/geo-agency-alternative", name: "GEO agency alternative", dir: "src/sublanding/solutions/geo-agency-alternative/", status: "new",
    concept: "A month ledger: a retainer invoice beside a Rankbox month, line by line, with one slider for retainer size.",
    q: [["generative engine optimization services", 1900, null, 18.23], ["generative engine optimization agency", 1300, 25, 20.51], ["geo agency", 590, null, 16.47], ["how to evaluate generative engine optimization geo agency tech stack", 10, 0, null]],
    hook: "Agency retainer vs software that does the daily work for the plan price.",
    build: "Concept module: retainer vs Rankbox cost calculator fed by dated, published agency price ranges. Fair section on what agencies do that software doesn't (PR, outreach, strategy), and a \"Run an agency? Use Rankbox under your retainer\" band linking /use-cases/seo-agencies.",
    truth: "No \"$10,000/mo\" unless a dated source says so. No citation tracking claim. Agencies are also Rankbox customers (Studio), so the tone compares jobs, it doesn't mock agencies.",
    overlap: ["/use-cases/seo-agencies"],
  }),
  P({
    phase: 2, route: "/solutions/geo-tools-comparison", name: "GEO tools comparison", dir: "src/sublanding/solutions/geo-tools-comparison/", status: "new",
    concept: "A field guide: a filterable landscape (track, fix, or both × self-serve or sales-led) with each vendor as a dated card. Rankbox is one card among them.",
    q: [["generative engine optimization tools", 880, null, 16.05], ["geo tools", 390, 20, 4.89], ["which other geo tools are like athena", 40, 0, null], ["which other geo tools are like scrunch ai", 40, 0, null], ["how to evaluate effectiveness of geo tool before purchasing", 40, 0, null], ["how is profound different from other geo/aeo tools", 30, 0, null]],
    hook: "A transparent matrix: enterprise-only tools, developer APIs and self-serve platforms, with who sells self-serve and who publishes.",
    build: "Concept module: a tool finder (track / fix / both, budget, self-serve or sales call). The matrix reads products.ts and starting-price.ts; Rankbox is one row with its real cells.",
    truth: "Rankbox's tracking cell says No until it ships. Athena and Scrunch facts checked on their own pages that day.",
    overlap: ["/solutions/aeo-tools", "blog: geo-tools-list", "blog: evaluate-geo-tool-before-purchasing", "/compare/profound-vs-peec-ai"],
  }),
  P({
    phase: 2, route: "/solutions/saas-citation-building", name: "SaaS citation building", dir: "src/sublanding/solutions/saas-citation-building/", status: "new", flag: "call",
    concept: "Two trails side by side: a guest post nobody quotes, and a reference page that keeps getting cited, drawn as their citations accumulate.",
    q: [["press release seo", 720, 28, 9.5], ["saas link building", 590, 19, 12.46]],
    hook: "Stop buying dead backlinks. Build reference pages that earn links and AI citations.",
    build: "Concept module: guest post vs reference page, side by side, with what each gets cited for. Then the loop.",
    truth: "Rankbox doesn't produce original benchmark studies or proprietary data; it writes cited articles. Your call needed: the link-building posts deliberately leave out the backlink exchange because they quote Google's link spam policy. Decide whether this page sells the exchange.",
    overlap: ["/features/authority-backlinks", "blog: link-building-ai-visibility-co-citation", "blog: does-link-building-help-ai-visibility"],
  }),
  P({
    phase: 2, route: "/solutions/agentic-seo", name: "Agentic SEO", dir: "src/sublanding/solutions/agentic-seo/", status: "new",
    concept: "Agent's-eye view: one product page shown twice, as people see it and as the stripped text an agent reads, with a toggle between the two.",
    q: [["generative engine optimization tool", 210, 35, 15.38], ["agentic seo", 170, 32, 7.53]],
    hook: "Optimize for the AI agents that research and buy for your customers.",
    build: "Concept module: the same product page seen by a person and by an agent (what the agent can and can't read). Then the machine-readable checklist and how Rankbox writes for it.",
    truth: "OpenAI Operator became ChatGPT agent, which is no longer available; Atlas stopped on 2026-08-09 (both verified 2026-09-30). Name agents that are current on the day of writing.",
    overlap: ["blog: what-is-agentic-seo", "blog: agentic-seo-autonomous-ai-buyers", "blog: prompt-zero-purchase-ai-agents-buy-software"],
  }),

  /* ---------------- Phase 3 alternatives: content & keyword ---------------- */
  P({
    phase: 3, route: "/alternatives/moz", name: "Moz alternative", dir: "src/sublanding/alternatives/moz/", status: "new", flag: "verify",
    concept: "A sorting board: Moz Pro's features dealt into \"keep a suite for this\" and \"Rankbox does this\", with the DA badge retired.",
    q: [["moz alternatives", 1600, 15, 28.75]],
    hook: "Stop paying to watch DA. Get named in ChatGPT, Perplexity and Claude, with articles published on autopilot.",
    build: "What Moz still does that Rankbox doesn't (rank tracking, link index, DA), so suite buyers know to keep one; dated Moz prices; switching steps.",
    truth: "PDF says Moz has zero AI search tracking; check Moz's current product pages before writing. Rankbox has no rank tracker, link index or authority metric.",
    overlap: ["/compare/semrush-vs-ahrefs"],
  }),
  P({
    phase: 3, route: "/alternatives/clearscope", name: "Clearscope alternative", dir: "src/sublanding/alternatives/clearscope/", status: "new", flag: "verify",
    concept: "One paragraph, two scores: a content-grade dial and a citation-readiness checklist run on the same text, visibly disagreeing.",
    q: [["clearscope alternatives", 260, 19, 20.26], ["surfer seo vs clearscope", 210, null, null], ["clearscope alternative", 170, 0, 20.26]],
    hook: "Stop grading keyword density. Write pages engines can lift an answer from, and publish them.",
    build: "Both scores run on one paragraph with the real CitationReadinessChecker rules; dated Clearscope prices; a link to the Surfer vs Clearscope head-to-head.",
    truth: "PDF price range $170–350+ must be re-checked; Clearscope may have added AI search features since.",
    overlap: ["/compare/surfer-seo-vs-clearscope", "/alternatives/surfer-seo"],
  }),
  P({
    phase: 3, route: "/alternatives/marketmuse", name: "MarketMuse alternative", dir: "src/sublanding/alternatives/marketmuse/", status: "new", flag: "verify",
    concept: "A topic model's score bubbles dissolving into the five questions engines actually get asked about that topic.",
    q: [["marketmuse alternatives", 210, 11, null]],
    hook: "Optimize for what AI engines quote instead of topic-score targets.",
    build: "Dated MarketMuse plans, what topic modelling is good for, and where Rankbox's question research differs.",
    truth: "\"Vector proximity\" isn't something Rankbox measures; don't claim it. MarketMuse was acquired by Siteimprove; check current plans and prices.",
    overlap: ["/alternatives/frase"],
  }),
  P({
    phase: 3, route: "/alternatives/copy-ai", name: "Copy.ai alternative", dir: "src/sublanding/alternatives/copy-ai/", status: "new", flag: "verify",
    concept: "A blank writing box that fills, then keeps going: sources, a score and a publish step appear, the gap between writing and shipping.",
    q: [["copy ai alternatives", 210, 8, null]],
    hook: "Beyond a blank-box writer: research, cited drafts and publishing in one loop.",
    build: "What Copy.ai sells today (checked that day), the gap between writing and publishing, and a fair matrix.",
    truth: "Copy.ai repositioned toward go-to-market workflows; describe what it sells today.",
    overlap: ["/alternatives/jasper", "/alternatives/writesonic"],
  }),
  P({
    phase: 3, route: "/alternatives/ubersuggest", name: "Ubersuggest alternative", dir: "src/sublanding/alternatives/ubersuggest/", status: "new", flag: "verify",
    concept: "A keyword list that unfolds: each keyword row opens into the AI questions people ask behind it.",
    q: [["ubersuggest alternatives", 210, 17, 9.57]],
    hook: "Graduate from keyword lists to answers engines quote.",
    build: "Plan limits from Ubersuggest's own page, dated; the keyword-to-questions idea run on a sample keyword.",
    truth: "\"Frequent crawler blocks\" and \"severe data limits\" are opinions from the PDF; state plan limits from Ubersuggest's own page instead.",
    overlap: [],
  }),

  /* ---------------- Phase 4 alternatives: SEO suites ---------------- */
  P({
    phase: 4, route: "/alternatives/brightedge", name: "BrightEdge alternative", dir: "src/sublanding/alternatives/brightedge/", status: "new", flag: "verify",
    concept: "A procurement memo: requirements down the left, BrightEdge, Conductor and Rankbox answers across, \"price on request\" shown plainly.",
    q: [["brightedge competitors", 590, null, 15.64], ["brightedge alternatives", 260, 16, 13.4], ["conductor alternatives", 40, 5, 8.19]],
    hook: "The generative-engine alternative to BrightEdge, self-serve at the plan price. Conductor gets its own section.",
    build: "The memo with BrightEdge and Conductor columns from their own pages, a Conductor section, and what enterprise suites do that Rankbox doesn't.",
    truth: "BrightEdge and Conductor both sell AI search features now; don't say they only report blue links. Their prices aren't published: say that, don't print \"$40,000/year\".",
    overlap: [],
  }),
  P({
    phase: 4, route: "/alternatives/spyfu", name: "SpyFu alternative", dir: "src/sublanding/alternatives/spyfu/", status: "new", flag: "verify",
    concept: "A competitor dossier with two folders: their Google ads, and the sources AI cites for them.",
    q: [["spyfu alternatives", 590, 22, 14.26]],
    hook: "From spying on Google Ads to seeing which sites AI engines cite instead of you.",
    build: "Dossier sections for ads, keywords and AI sources. The PDF's AI competitor gap scanner waits for tracking; v1 links the Prompt Kit.",
    truth: "Rankbox has no ad or keyword-spy data.",
    overlap: [],
  }),
  P({
    phase: 4, route: "/alternatives/se-ranking", name: "SE Ranking alternative", dir: "src/sublanding/alternatives/se-ranking/", status: "new", flag: "verify",
    concept: "An agency client report: Google positions on top, and the AI search section the client keeps asking about below.",
    q: [["se ranking alternatives", 70, 12, 13.48]],
    hook: "For teams whose clients now ask about ChatGPT, not just Google positions.",
    build: "A fair comparison that includes SE Ranking's own AI tracker, and where Rankbox's writing and publishing loop sits beside it.",
    truth: "SE Ranking sells an AI results tracker; the PDF's premise that it lacks AI visibility is likely wrong. Check and compare fairly.",
    overlap: [],
  }),
  P({
    phase: 4, route: "/alternatives/mangools", name: "Mangools alternative", dir: "src/sublanding/alternatives/mangools/", status: "new", flag: "verify",
    concept: "A toolbox shelf: each Mangools tool on a shelf with its Rankbox counterpart or a \"keep it\" tag. Light, friendly, compact.",
    q: [["mangools alternatives", 170, 15, 16.55]],
    hook: "The clean, affordable feel of Mangools, aimed at AI answers and publishing.",
    build: "Tool-by-tool shelf with dated prices. Listed twice in the PDF (under SpyFu and on its own); built once, here.",
    truth: "Rankbox has no SERP tracker like SERPWatcher.",
    overlap: [],
  }),
  P({
    phase: 4, route: "/alternatives/serpstat", name: "Serpstat alternative", dir: "src/sublanding/alternatives/serpstat/", status: "new", flag: "verify",
    concept: "A migration checklist: export, map, replace, with each Serpstat module ticked or flagged.",
    q: [["serpstat alternatives", 320, 3, null]],
    hook: "Next-generation AI search alternative to Serpstat.",
    build: "A module-by-module migration checklist with dated Serpstat prices.",
    truth: "PDF says \"monitor legacy SERPs and AI engines from one platform\": Rankbox does neither today. Drop that line.",
    overlap: [],
  }),

  /* ---------------- Phase 5 alternatives: audit & reporting ---------------- */
  P({
    phase: 5, route: "/alternatives/screaming-frog", name: "Screaming Frog alternative", dir: "src/sublanding/alternatives/screaming-frog/", status: "new", flag: "verify",
    concept: "A desktop crawler window that becomes a cloud check: the AI Search Audit runs live on your URL in a crawler-style table.",
    q: [["screaming frog alternatives", 170, 19, 5.95], ["contentking alternatives", 50, 2, null]],
    hook: "A cloud check of what AI crawlers can reach, with no desktop crawl. ContentKing gets its own section.",
    build: "The Phase 1 AI Search Audit runs inside the page; a ContentKing section; what a desktop crawler still does better.",
    truth: "Screaming Frog can crawl as GPTBot by setting the user agent; don't say it can't simulate AI bots. ContentKing is now part of Conductor.",
    overlap: ["/tools/ai-search-audit", "/tools/robots-txt-tester"],
  }),
  P({
    phase: 5, route: "/alternatives/woorank", name: "WooRank alternative", dir: "src/sublanding/alternatives/woorank/", status: "new", flag: "verify",
    concept: "Two report cards stapled together for the same URL: the HTML audit card and the answer-readiness card.",
    q: [["woorank alternatives", 320, 9, null]],
    hook: "Move past basic HTML audits to answer readiness.",
    build: "Both cards for the visitor's URL: WooRank-style HTML checks described, Rankbox's answer-readiness checks run live.",
    truth: "Drop \"vector proximity\" and \"entity graph completeness\" scores; Rankbox doesn't compute them.",
    overlap: ["/tools/aeo-checker"],
  }),
  P({
    phase: 5, route: "/alternatives/seobility", name: "Seobility alternative", dir: "src/sublanding/alternatives/seobility/", status: "new", flag: "verify",
    concept: "A severity ladder: crawl issues at the bottom, AI access and answer issues at the top, each rung marked with the tools that cover it.",
    q: [["seobility alternatives", 140, 15, 9.92]],
    hook: "From crawl checklists to AI crawler access and answer-ready pages.",
    build: "The ladder, with each tool's coverage taken from its own feature pages.",
    truth: "\"Citation gap analysis\" isn't shipped; leave it out.",
    overlap: ["/tools/ai-search-audit"],
  }),
  P({
    phase: 5, route: "/alternatives/agencyanalytics", name: "AgencyAnalytics alternative", dir: "src/sublanding/alternatives/agencyanalytics/", status: "new", flag: "weak",
    concept: "A client dashboard with an empty \"AI search\" widget, and how an agency fills it with Studio and the free scans.",
    q: [["agencyanalytics alternatives", 480, 20, 14.58], ["whatagraph alternatives", 50, 0, 31.72]],
    hook: "When clients ask for their AI search report. Whatagraph gets its own section.",
    build: "The dashboard, a Whatagraph section, and a plain line that Rankbox is not a reporting tool.",
    truth: "Rankbox has no white-label reporting, share-of-model tracking or AI referral attribution. Weak fit: it doesn't replace a reporting tool.",
    overlap: ["/use-cases/seo-agencies"],
  }),

  /* ---------------- Phase 6 alternatives: GEO trackers ---------------- */
  P({
    phase: 6, route: "/alternatives/peec-ai", name: "Peec AI alternative", dir: "src/sublanding/alternatives/peec-ai/", status: "new", flag: "verify",
    concept: "A diptych: a tracker chart with a lost prompt on the left, the article that answers it on the right.",
    q: [["peec ai", 1600, null, null], ["peec ai alternatives", 110, 11, 21.17], ["peec ai competitors", 110, null, 20.8]],
    hook: "Don't just watch the gap: publish the reference articles engines cite.",
    build: "The diptych, plus the \"trackers show the gap, Rankbox closes it\" argument; dated Peec prices.",
    truth: "Until tracking ships, Rankbox's tracking row reads No. Check whether Peec now offers content actions before saying it has none.",
    overlap: ["/compare/profound-vs-peec-ai", "/solutions/ai-search-visibility"],
  }),
  P({
    phase: 6, route: "/alternatives/profound", name: "Profound alternative", dir: "src/sublanding/alternatives/profound/", status: "new", flag: "verify",
    concept: "A calendar: weeks of \"book a demo\" on one side, the first useful day with Rankbox marked on the other.",
    q: [["best alternatives to profound", 40, null, null], ["profound alternative", 20, 0, 16.76], ["cheaper alternatives to profound aeo", null, null, null]],
    hook: "Self-serve GEO: no sales call, start today.",
    build: "Profound's access model and prices as published (or \"on request\"), and the first week with Rankbox, day by day.",
    truth: "PDF says \"tracking in 60 seconds\" and a \"2-day trial\": the trial is 7 days and Rankbox doesn't track. Check whether Profound now sells a self-serve tier.",
    overlap: ["/compare/profound-vs-peec-ai"],
  }),
  P({
    phase: 6, route: "/alternatives/scrunch-ai", name: "Scrunch AI alternative", dir: "src/sublanding/alternatives/scrunch-ai/", status: "new", flag: "verify",
    concept: "A job lens: toggle monitor, optimize or publish and each tool lights up for the jobs it does.",
    q: [["scrunch ai", 1900, null, 14.74], ["scrunch ai alternatives", 70, 6, null], ["which other geo tools are like scrunch ai", 40, 0, null], ["are there any other aeo tools like scrunch ai", 20, 0, null]],
    hook: "The self-serve alternative to Scrunch, with publishing on autopilot.",
    build: "The job lens across Scrunch and Rankbox, with facts dated from Scrunch's own pages.",
    truth: "Same tracking caveat as Peec.",
    overlap: ["/solutions/geo-tools-comparison"],
  }),
  P({
    phase: 6, route: "/alternatives/otterly-ai", name: "Otterly AI alternative", dir: "src/sublanding/alternatives/otterly-ai/", status: "new", flag: "verify",
    concept: "An alert feed (\"you lost a citation\") where each alert carries the action Rankbox takes next.",
    q: [["otterly ai", 480, null, null], ["otterly ai alternatives", 50, 0, null]],
    hook: "From monitoring to fixing: Otterly reports who got cited, Rankbox writes the page to take the spot.",
    build: "The alert feed, with Otterly's current features checked that day.",
    truth: "Check Otterly's current features; \"only reports mentions\" may be out of date.",
    overlap: [],
  }),
  P({
    phase: 6, route: "/alternatives/ziptie", name: "Ziptie alternative", dir: "src/sublanding/alternatives/ziptie/", status: "new", flag: "verify",
    concept: "An AI Overview source carousel, with your site sliding into one slot as the page explains how that slot is earned.",
    q: [["ziptie ai", 50, 12, 12.03], ["ziptie alternatives", 20, 0, null], ["ziptie dev", 20, 0, null]],
    hook: "Beyond auditing AI Overviews: publish the reference pages that win citations.",
    build: "The carousel explainer, with Ziptie's engine coverage checked that day.",
    truth: "PDF says Ziptie covers only AI Overviews; check, it may track ChatGPT and Perplexity too.",
    overlap: [],
  }),
  P({
    phase: 6, route: "/alternatives/brand24", name: "Brand24 alternative", dir: "src/sublanding/alternatives/brand24/", status: "new", flag: "verify",
    concept: "Two streams: social mentions on one side, an AI answer about the same brand on the other, showing where each tool listens.",
    q: [["brand24 alternative", 20, 0, 10.9]],
    hook: "From social listening to shaping what AI answers say.",
    build: "Listening vs answering, with Brand24's AI features checked that day.",
    truth: "Brand24 has added AI features; check before saying it can't see AI answers. Rankbox doesn't do social listening.",
    overlap: [],
  }),

  /* ---------------- Phase 7 platforms ---------------- */
  P({
    phase: 7, route: "/solutions/magento-ai-seo", name: "Magento AI SEO", dir: "src/sublanding/solutions/magento-ai-seo/", status: "new",
    concept: "A Magento admin with layered navigation, marking the crawl traps AI bots fall into, and an article arriving through the API.",
    q: [["magento seo", 3600, 28, 25.94], ["bigcommerce seo", 2900, 31, 9.55]],
    hook: "AI search optimization for Adobe Commerce and Magento without custom module work. BigCommerce gets its own section.",
    build: "Platform scene: Magento admin with a Rankbox article arriving through the API. Checklist: faceted-navigation canonicals, layered nav crawl traps, Product schema, rendering for AI bots.",
    truth: "No Magento or BigCommerce app exists; articles arrive through the API a developer wires once. No \"schema syndication\" or \"faceted catalog entity mapping\" claims.",
    overlap: ["/integrations/api", "/use-cases/ecommerce"],
  }),
  P({
    phase: 7, route: "/solutions/headless-cms-seo", name: "Headless CMS SEO", dir: "src/sublanding/solutions/headless-cms-seo/", status: "new",
    concept: "Code and content split: a Next.js/Sanity file tree on the left, the HTML an AI bot actually receives on the right, plus a live llms.txt validator.",
    q: [["headless cms seo", 720, 19, null]],
    hook: "Turn Sanity, Contentful, Strapi or Next.js into a source AI engines can read and cite.",
    build: "Platform scene: a Sanity-style studio receiving an article from the pull API. Checklist: server rendering for AI bots (most don't run JavaScript), JSON-LD, llms.txt. Adds a small real llms.txt validator to the free tools.",
    truth: "The API is pull-based (/articles?since=), not webhooks. Say exactly that.",
    overlap: ["/integrations/api", "/tools/llms-txt-generator", "blog: dynamic-rendering-prerendering-ai-crawlers"],
  }),
  P({
    phase: 7, route: "/solutions/shopify-ai-seo", name: "Shopify AI SEO", dir: "src/sublanding/solutions/shopify-ai-seo/", status: "new",
    concept: "A phone-sized storefront under a ChatGPT shopping question; the blog post that answers it slides into the store.",
    q: [["shopify ai seo", 20, 0, 8.58]],
    hook: "Get your store named when shoppers ask ChatGPT for the best product under a budget.",
    build: "Platform scene: Shopify admin blog with the article arriving. Status pill follows addonLive (app tested on a dev store, App Store review pending).",
    truth: "The app publishes blog articles; it doesn't scan the catalog or write product spec pages. Say \"in review\" until addonLive flips.",
    overlap: ["/integrations/shopify (presents the app as shipped)", "/use-cases/ecommerce"],
  }),
  P({
    phase: 7, route: "/solutions/webflow-ai-seo", name: "Webflow AI SEO", dir: "src/sublanding/solutions/webflow-ai-seo/", status: "new",
    concept: "The Webflow CMS panel with a collection item appearing, beside a ledger showing your own edits are never overwritten.",
    q: [["webflow ai seo", 20, 0, 14.24]],
    hook: "Turn your Webflow CMS into a source AI engines cite.",
    build: "Platform scene: Webflow CMS collection receiving an item. Status pill follows addonLive (app deployed, Marketplace approval pending).",
    truth: "The app pushes server-side over OAuth; it isn't a webhook. Items edited in Webflow are never overwritten: a real selling point.",
    overlap: ["/integrations/webflow", "/use-cases/saas (Webflow scene)"],
  }),
  P({
    phase: 7, route: "/solutions/hubspot-ai-seo", name: "HubSpot AI SEO", dir: "src/sublanding/solutions/hubspot-ai-seo/", status: "new", flag: "weak",
    concept: "A HubSpot blog editor beside a topic-cluster map, with the honest route an article takes to get in (API or paste).",
    q: [["hubspot ai seo", 20, 0, 8.75]],
    hook: "Make your HubSpot blog a source AI engines can read and quote.",
    build: "Platform scene: HubSpot blog editor. Checklist: HubSpot's own AI crawler settings, schema, topic clusters.",
    truth: "There's no HubSpot integration. Publishing means wiring the API into HubSpot's blog API, or pasting. Weak fit until a HubSpot app exists.",
    overlap: ["/integrations/api"],
  }),
  P({
    phase: 7, route: "/solutions/no-code-ai-seo", name: "No-code AI SEO", dir: "src/sublanding/solutions/no-code-ai-seo/", status: "new",
    concept: "Three device frames for Ghost, Bubble and Notion, each showing what an AI bot can and can't read there.",
    q: [["notion seo", 40, 29, null], ["bubble seo", 20, 0, null], ["ghost cms seo", 20, 0, null]],
    hook: "AI search for apps and sites built on Ghost, Bubble and Notion.",
    build: "Three columns, one per platform, each with what AI bots can and can't read there and how articles get in.",
    truth: "\"Inject server-rendered pages into Bubble without touching your database\" isn't real. Ghost has an Admin API (a fit); Bubble and Notion need a developer.",
    overlap: ["/integrations/api"],
  }),

  /* ---------------- Phase 8 engines & entities ---------------- */
  P({
    phase: 8, route: "/solutions/searchgpt-seo", name: "SearchGPT SEO", dir: "src/sublanding/solutions/searchgpt-seo/", status: "new",
    concept: "A rename strip (SearchGPT → ChatGPT search) as the hero, then the OAI-SearchBot readability scan.",
    q: [["searchgpt seo", 170, 17, null], ["searchgpt optimization", 50, 19, 8.09]],
    hook: "Optimize for OpenAI's search, with a free OAI-SearchBot readability scan.",
    build: "Scan: robots.txt rules for OAI-SearchBot and GPTBot, schema and server-rendered text, using the real robots tester.",
    truth: "SearchGPT became ChatGPT search in late 2024; keep the query in the H1 and explain the rename in the first paragraph. Drop \"vector proximity scoring\".",
    overlap: ["/ai-seo/chatgpt (guide hero is frozen; link to it)", "blog: what-is-oai-searchbot"],
  }),
  P({
    phase: 8, route: "/solutions/grok-ai-seo", name: "Grok AI SEO", dir: "src/sublanding/solutions/grok-ai-seo/", status: "new",
    concept: "A real-time feed: posts streaming into an answer, showing the kinds of sources a real-time engine leans on.",
    q: [["grok seo", 20, 0, null]],
    hook: "Win citations in Grok's real-time answers.",
    build: "Facts reuse src/data/ai-seo/content/grok.ts; the page is about what Rankbox does for real-time engines.",
    truth: "\"Grok 2 & 3\" is out of date and xAI rebranded to SpaceXAI. No free Grok simulation without API budget. Similar to /ai-seo/grok: give it the commercial angle (what Rankbox does about it).",
    overlap: ["/ai-seo/grok"],
  }),
  P({
    phase: 8, route: "/tools/semantic-seo-tool", name: "Semantic SEO tool", dir: "src/sublanding/tools/semantic-seo-tool/", status: "new",
    concept: "A highlighter: your page's copy with entities underlined by type, each linked in a margin to its Wikidata match.",
    q: [["what is entity seo", 140, null, null], ["semantic seo tool", 30, 0, 9.69]],
    hook: "Entity-first SEO: see the entities a page names and whether engines can connect them to you.",
    build: "Real free tool: entities in headings and copy, schema @types, sameAs links, and a Wikidata match for the brand.",
    truth: "PDF route /features/semantic-seo-tool is reserved for shipped Rankbox features, so this uses the PDF's own alternate, /tools/semantic-seo-tool. Nobody can \"map your brand into LLM vector databases\".",
    overlap: ["blog: entity-seo-strategy", "blog: wikidata-seo", "glossary entity pages"],
  }),
  P({
    phase: 8, route: "/solutions/knowledge-graph-seo", name: "Knowledge graph SEO", dir: "src/sublanding/solutions/knowledge-graph-seo/", status: "new",
    concept: "A graph you build: add a fact about your brand and a node and edge appear, until the entity is unambiguous.",
    q: [["knowledge graph seo", 1300, 36, null], ["topical map generator", 50, 26, null], ["entity seo tool", 40, 21, null]],
    hook: "Make your brand the unambiguous entity engines connect to your topics.",
    build: "Concept module: an entity relationship view built from the semantic tool's output plus Rankbox's topic map.",
    truth: "PDF route /features/entity-seo uses the PDF's alternate, /solutions/knowledge-graph-seo. Google's Knowledge Graph can't be written to; say what influences it.",
    overlap: ["blog: seo-knowledge-graph", "blog: knowledge-graph-for-ai", "blog: entity-authority-seo"],
  }),

  /* ---------------- Phase 9 SaaS & developers ---------------- */
  P({
    phase: 9, route: "/solutions/ai-seo-for-saas", name: "AI SEO for SaaS", dir: "src/sublanding/solutions/ai-seo-for-saas/", status: "new",
    concept: "A \"best X software\" answer with five slots, and a walk through what puts a product into each slot.",
    q: [["ai seo for saas", 30, 0, null]],
    hook: "Win the \"best [category] software\" answer in ChatGPT.",
    build: "Angle: the shortlist answer. Comparison, alternatives and pricing-clarity pages that engines quote when buyers ask for the best tool.",
    truth: "Three SaaS pages plus /use-cases/saas: each needs its own angle (this one = the shortlist).",
    overlap: ["/use-cases/saas", "blog: how-saas-companies-use-ai-for-seo-content-creation"],
  }),
  P({
    phase: 9, route: "/solutions/saas-aeo", name: "SaaS AEO", dir: "src/sublanding/solutions/saas-aeo/", status: "new",
    concept: "Docs before and after: a dense docs page transformed, section by section, into answer-ready blocks.",
    q: [["saas aeo", 40, 0, null], ["ai search visibility service", 40, 0, null], ["b2b aeo", 10, 0, null]],
    hook: "Win the \"best [category] software\" answer in ChatGPT and Claude with comparison tables, citable docs and a clear entity.",
    build: "Angle: answer-engine formatting of product content: docs, integration pages, pricing and changelog that engines can lift answers from.",
    truth: "No claim that Rankbox builds \"entity graphs\".",
    overlap: ["/solutions/ai-seo-for-saas", "/use-cases/saas"],
  }),
  P({
    phase: 9, route: "/solutions/b2b-saas-content", name: "B2B SaaS content", dir: "src/sublanding/solutions/b2b-saas-content/", status: "new",
    concept: "An inverted funnel: top-of-funnel posts shrinking into AI summaries while bottom-of-funnel assets keep getting cited.",
    q: [["b2b saas content marketing", 320, 15, null]],
    hook: "Turn your SaaS into the source LLMs cite.",
    build: "Angle: the content strategy shift from top-of-funnel glossaries (now summarised by AI Overviews) to bottom-of-funnel reference assets.",
    truth: "\"Organic traffic dropping 30–50%\" needs a cited study or goes.",
    overlap: ["/solutions/ai-seo-for-saas", "/solutions/saas-aeo"],
  }),
  P({
    phase: 9, route: "/solutions/developer-marketing-ai-seo", name: "Developer marketing AI SEO", dir: "src/sublanding/solutions/developer-marketing-ai-seo/", status: "new",
    concept: "An IDE: a coding assistant recommending a library, with docs and llms.txt as the levers and the real llms.txt adoption figures beside it.",
    q: [["developer marketing agency", 210, 4, 13.41]],
    hook: "Get your API or SDK recommended inside Cursor, Claude and ChatGPT.",
    build: "Unique content: the real Phase 3 study (llms.txt adoption is 50% among dev tools), the MCP server, llms.txt and API docs as the levers.",
    truth: "Rankbox doesn't generate API references or benchmarks; it writes the cited articles around them.",
    overlap: ["/integrations/mcp", "blog: state-of-llms-txt-adoption", "blog: github-readme-ai-seo"],
  }),
  P({
    phase: 9, route: "/solutions/cybersecurity-ai-seo", name: "Cybersecurity AI SEO", dir: "src/sublanding/solutions/cybersecurity-ai-seo/", status: "new",
    concept: "A CISO's vendor evaluation sheet (controls, certifications, integrations) and the answer an engine assembles from it.",
    q: [["cybersecurity seo", 590, 13, null], ["cyber security seo", 480, null, null], ["seo for cybersecurity", 320, null, null], ["seo for cyber security", 110, null, 18.35]],
    hook: "Get your security product into the answer when a CISO asks Perplexity to compare vendors.",
    build: "Prompt map for security buyers; entity facts that matter (certifications such as SOC 2 and ISO 27001 stated plainly and sourced).",
    truth: "The PDF's \"scan for hallucinated certifications\" needs tracking; v1 gives the Prompt Kit preset.",
    overlap: [],
  }),

  /* ---------------- Phase 10 commerce & agents ---------------- */
  P({
    phase: 10, route: "/solutions/ecommerce-aeo", name: "E-commerce AEO", dir: "src/sublanding/solutions/ecommerce-aeo/", status: "new",
    concept: "An annotated buyer's guide: each annotation names what makes that part of the page quotable.",
    q: [["ecommerce aeo", 30, 0, null], ["ai seo for ecommerce", 30, 0, null], ["how to get recommended by chatgpt", 20, 0, 5.03]],
    hook: "Win product recommendations in ChatGPT and Perplexity with buyer guides and comparison pages built for AI shopping.",
    build: "Angle: buyer-guide and comparison content for stores. Product schema checklist.",
    truth: "\"Structured product entity mapping\" isn't a Rankbox feature; the free schema generator is.",
    overlap: ["/use-cases/ecommerce", "/tools/get-recommended-by-chatgpt"],
  }),
  P({
    phase: 10, route: "/solutions/chatgpt-shopping", name: "ChatGPT shopping", dir: "src/sublanding/solutions/chatgpt-shopping/", status: "new", flag: "verify",
    concept: "A product card from a shopping answer, dissected: title, price, merchant, reviews, and which of them a store controls.",
    q: [["how to optimize for chatgpt shopping", 50, 0, null], ["chatgpt shopping optimization", 10, 0, null]],
    hook: "Get your products recommended in ChatGPT shopping answers.",
    build: "Angle: the how-to. What ChatGPT's shopping results draw on, per OpenAI's own docs, and what a store controls.",
    truth: "Drop \"vector proximity matching\". Similar to /solutions/agentic-commerce: this page is the merchant how-to, that one is the protocol and checkout.",
    overlap: ["/solutions/agentic-commerce"],
  }),
  P({
    phase: 10, route: "/solutions/agentic-commerce", name: "Agentic commerce", dir: "src/sublanding/solutions/agentic-commerce/", status: "new", flag: "verify",
    concept: "A checkout drawn from the agent's side, step by step, with a readiness checklist against OpenAI's published spec.",
    q: [["openai instant checkout chatgpt", 1600, null, null], ["chatgpt shopping", 1300, null, null], ["agentic commerce protocol", 880, null, 7.95]],
    hook: "Prepare your catalog for AI buyers.",
    build: "Real ACP readiness checklist from OpenAI's published spec, plus the content side Rankbox does.",
    truth: "Rankbox doesn't integrate ACP or product feeds. Check Instant Checkout's current status first; OpenAI's agent products changed twice in 2026.",
    overlap: ["blog: prompt-zero-purchase-ai-agents-buy-software", "/use-cases/ecommerce"],
  }),

  /* ---------------- Phase 11 legal ---------------- */
  P({
    phase: 11, route: "/solutions/personal-injury-ai-seo", name: "Personal injury AI SEO", dir: "src/sublanding/solutions/personal-injury-ai-seo/", status: "new",
    concept: "A 72-hour timeline after a crash: the questions a victim asks AI at each hour, and where a firm's pages answer them.",
    q: [["personal injury lawyer marketing", 1900, 29, 91.65]],
    hook: "Get cited when accident victims ask ChatGPT who to call, instead of paying hundreds per click.",
    build: "Prompt map (urgent, compare, choose). Schema: LegalService, Attorney, Person with credentials. Rules: ABA Model Rules 7.1–7.3, state rules on results and \"specialist\".",
    truth: "\"$800/click\" needs a dated source. Verdict pages carry each state's past-results disclaimer.",
    overlap: [],
  }),
  P({
    phase: 11, route: "/solutions/family-law-ai-seo", name: "Family law AI SEO", dir: "src/sublanding/solutions/family-law-ai-seo/", status: "new",
    concept: "A quiet reading room with a state picker: the same divorce question answered differently by jurisdiction.",
    q: [["family law seo", 880, 19, 73.53]],
    hook: "Be on the shortlist when a spouse researches divorce in ChatGPT before calling anyone.",
    build: "Angle: private, research-heavy prompts by jurisdiction (equitable distribution, custody factors).",
    truth: "Content explains the law in general; it never advises a reader.",
    overlap: [],
  }),
  P({
    phase: 11, route: "/solutions/criminal-defense-ai-seo", name: "Criminal defense AI SEO", dir: "src/sublanding/solutions/criminal-defense-ai-seo/", status: "new",
    concept: "2 a.m.: a dark, calm page of the urgent questions after an arrest, and what a firm's page needs to answer them.",
    q: [["criminal defense seo", 260, 9, 79.34]],
    hook: "Find out what ChatGPT says when someone asks for the top defense lawyer in your county.",
    build: "Angle: emergency prompts (arrest, DUI) and white-collar research prompts.",
    truth: "Same advertising rules as PI; no outcome promises.",
    overlap: [],
  }),
  P({
    phase: 11, route: "/solutions/immigration-law-ai-seo", name: "Immigration law AI SEO", dir: "src/sublanding/solutions/immigration-law-ai-seo/", status: "new",
    concept: "A visa explorer: pick O-1, EB-1A, H-1B or L-1 and see the criteria questions founders ask about it.",
    q: [["immigration lawyer marketing", 390, 11, 20.62]],
    hook: "Get cited when founders ask how to file an EB-1A or O-1.",
    build: "Angle: corporate immigration (H-1B, L-1, EB-1, O-1) criteria explainers that engines quote.",
    truth: "USCIS criteria change; every explainer carries a reviewed-on date.",
    overlap: [],
  }),
  P({
    phase: 11, route: "/solutions/legal-ai-seo", name: "Law firm AI SEO", dir: "src/sublanding/solutions/legal-ai-seo/", status: "new",
    concept: "A floor plan of a firm: each practice area a room that opens its AI questions, linking down to the four practice pages.",
    q: [["how to use ai for your law firm's seo", 30, 0, null], ["law firm ai seo", 20, 0, null], ["can seo improve a law firm's ai visibility", 10, 0, null]],
    hook: "Protect your practice in AI search.",
    build: "The hub for the four practice-area pages: what all firms share, and links down to each.",
    truth: "Rules box generalised across practice areas.",
    overlap: ["the four practice-area pages above"],
  }),

  /* ---------------- Phase 12 home services ---------------- */
  P({
    phase: 12, route: "/solutions/hvac-ai-seo", name: "HVAC AI SEO", dir: "src/sublanding/solutions/hvac-ai-seo/", status: "new",
    concept: "A thermostat dial: drag the outdoor temperature and the questions change from \"AC blowing warm\" to \"furnace won't light\".",
    q: [["hvac marketing agency", 2400, 21, 25.75], ["plumber marketing", 1600, 22, 25.95], ["hvac seo agency", 1300, 26, 63.08]],
    hook: "HVAC SEO without the agency: get named when the AC dies and someone asks AI who's open now.",
    build: "Schema: HVACBusiness, Plumber, areaServed, openingHours. Prompt map by season. A free \"does AI name you\" Prompt Kit preset.",
    truth: "Siri's local answers come from Apple Maps and its partners; Rankbox can't change them. No \"brand certification schemas\".",
    overlap: ["/use-cases/local-businesses", "blog: local-seo-in-chatgpt"],
  }),
  P({
    phase: 12, route: "/solutions/roofing-ai-seo", name: "Roofing AI SEO", dir: "src/sublanding/solutions/roofing-ai-seo/", status: "new",
    concept: "A material swatch board (TPO, EPDM, metal, tile, shingle); each swatch opens the buyer questions and the specs engines quote.",
    q: [["roofing seo agency", 720, 18, 23.43], ["commercial roofing marketing (cluster)", 2400, null, null]],
    hook: "Be the contractor AI names for TPO, metal or storm-damage jobs.",
    build: "Schema: RoofingContractor. Material-by-material topic map (TPO, EPDM, metal, tile, insurance restoration).",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 12, route: "/solutions/solar-ai-seo", name: "Solar AI SEO", dir: "src/sublanding/solutions/solar-ai-seo/", status: "new",
    concept: "A state picker for net metering and incentives, each answer dated, with the questions homeowners ask in that state.",
    q: [["solar marketing", 880, 17, 8.57], ["solar company seo", 390, 16, null]],
    hook: "Be the installer AI cites when homeowners research going solar.",
    build: "Angle: policy-heavy questions (net metering by state, incentives) answered with dated sources.",
    truth: "Incentive and net-metering facts expire; every one is dated. \"Utility rebate schemas\" don't exist.",
    overlap: [],
  }),
  P({
    phase: 12, route: "/solutions/landscaping-ai-seo", name: "Landscaping AI SEO", dir: "src/sublanding/solutions/landscaping-ai-seo/", status: "new",
    concept: "A four-season wheel of commercial contracts (snow, mowing, hardscape, irrigation) with what property managers ask each season.",
    q: [["landscaping seo", 1900, 23, 13.76]],
    hook: "Turn a portfolio of photos into answers that win commercial grounds contracts.",
    build: "Angle: commercial contracts (HOA, campuses, snow removal) where the buyer asks AI for a shortlist.",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 12, route: "/solutions/self-storage-ai-seo", name: "Self-storage AI SEO", dir: "src/sublanding/solutions/self-storage-ai-seo/", status: "new",
    concept: "The commission calculator is the hero: enter unit rent and aggregator fee, see what a direct renter is worth.",
    q: [["self storage seo", 390, 2, 44.4], ["self storage marketing agency", 170, 4, 42.46]],
    hook: "Get renters sent to your site, not an aggregator.",
    build: "Schema: SelfStorage with amenities. A commission calculator where the operator enters their own rates.",
    truth: "No aggregator commission figure unless it comes from the aggregator's own published terms.",
    overlap: [],
  }),

  /* ---------------- Phase 13 healthcare practices ---------------- */
  P({
    phase: 13, route: "/solutions/aesthetic-ai-seo", name: "Plastic surgery & med spa AI SEO", dir: "src/sublanding/solutions/aesthetic-ai-seo/", status: "new",
    concept: "A procedure menu card (rhinoplasty, Morpheus8, fillers): each item shows the patient questions and the rules on photos and claims.",
    q: [["plastic surgery seo", 2400, 21, 21.42], ["medspa seo", 480, 13, 23.85]],
    hook: "Be the practice AI names for a procedure in your city.",
    build: "Schema: MedicalClinic, Physician with hasCredential. Rules: HIPAA authorization for photos and testimonials, FTC health claims, state board rules on before-and-after images.",
    truth: "\"Apple Intelligence recommends your practice\" can't be promised.",
    overlap: [],
  }),
  P({
    phase: 13, route: "/solutions/dso-ai-seo", name: "DSO AI SEO", dir: "src/sublanding/solutions/dso-ai-seo/", status: "new",
    concept: "A grid of practice cards whose hours, insurance and dentists drift out of sync, then snap back once the facts are published.",
    q: [["dental seo agency", 2400, 33, 26.02], ["dso marketing", 320, 7, 10.5]],
    hook: "Keep 50 practices' insurance networks, hours and dentists straight in AI answers.",
    build: "Schema: Dentist per location, accepted insurance stated in plain text. Studio pricing per site, shown honestly.",
    truth: "Rankbox doesn't sync data to engines; it publishes pages engines read.",
    overlap: [],
  }),
  P({
    phase: 13, route: "/solutions/chiropractic-ai-seo", name: "Chiropractic AI SEO", dir: "src/sublanding/solutions/chiropractic-ai-seo/", status: "new",
    concept: "A body map: tap a pain area to see the condition questions patients ask AI, with claims kept inside FTC rules.",
    q: [["chiropractic seo", 1900, 25, 24.34]],
    hook: "Be the specialist AI names for a condition, not just a clinic on a map.",
    build: "Angle: condition-specific prompts (sciatica, decompression) with FTC-safe claims.",
    truth: "Treatment claims need evidence; the rules box says what can't be claimed.",
    overlap: [],
  }),
  P({
    phase: 13, route: "/solutions/orthodontist-ai-seo", name: "Orthodontist AI SEO", dir: "src/sublanding/solutions/orthodontist-ai-seo/", status: "new",
    concept: "A decision tree a parent walks (age, bite, budget, aligners or braces) with the questions at each branch.",
    q: [["orthodontist seo", 590, 14, 28.89]],
    hook: "Get cited when parents ask AI which aligner fits and who offers it nearby.",
    build: "Angle: treatment-comparison prompts (aligners vs braces) answered neutrally.",
    truth: "Aligner brand names are trademarks; compare without implying endorsement.",
    overlap: [],
  }),
  P({
    phase: 13, route: "/solutions/veterinary-ai-seo", name: "Veterinary AI SEO", dir: "src/sublanding/solutions/veterinary-ai-seo/", status: "new",
    concept: "A 24-hour emergency clock: what pet owners ask at each hour, and the opening-hours facts engines need.",
    q: [["veterinary seo", 590, 6, 43.49]],
    hook: "Be the clinic AI names in an emergency.",
    build: "Schema: VeterinaryCare with openingHours and emergency services. Emergency and specialty prompt map.",
    truth: "Siri and Maps answers aren't Rankbox's to change.",
    overlap: [],
  }),

  /* ---------------- Phase 14 behavioral health & life sciences ---------------- */
  P({
    phase: 14, route: "/solutions/therapy-ai-seo", name: "Therapy practice AI SEO", dir: "src/sublanding/solutions/therapy-ai-seo/", status: "new",
    concept: "A calm, low-contrast directory of modalities (EMDR, CBT, couples, ADHD) in plain words, ethics rules up front, nothing salesy.",
    q: [["therapist seo", 1300, 27, 16.02]],
    hook: "Help people find the right care when they ask AI.",
    build: "Angle: modality and specialization pages (EMDR, ADHD, couples) and insurance networks in plain text.",
    truth: "APA and ACA ethics codes restrict soliciting client testimonials; the page must not suggest reviews from clients.",
    overlap: [],
  }),
  P({
    phase: 14, route: "/solutions/rehab-ai-seo", name: "Addiction treatment AI SEO", dir: "src/sublanding/solutions/rehab-ai-seo/", status: "new",
    concept: "A family's question journey from first worry to admission, with accreditation and insurance facts as checkable cards.",
    q: [["addiction treatment marketing", 1000, 16, null], ["rehab seo", 480, 20, 50]],
    hook: "Be accurately represented when families ask AI for treatment options.",
    build: "Rules: LegitScript certification for ads, patient-brokering law (EKRA), SAMHSA resources. Accreditation (CARF, Joint Commission) stated with sources.",
    truth: "Highest-care page on the site: no outcome claims and no urgency tactics.",
    overlap: [],
  }),
  P({
    phase: 14, route: "/solutions/concierge-medicine-ai-seo", name: "Concierge medicine AI SEO", dir: "src/sublanding/solutions/concierge-medicine-ai-seo/", status: "new",
    concept: "A membership card, with the executive-health questions and the credential facts engines look for.",
    q: [["concierge medicine marketing", 260, 9, 8.45]],
    hook: "Be the physician AI names when executives ask for concierge care nearby.",
    build: "Schema: Physician with hospital affiliation and credentials.",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 14, route: "/solutions/biotech-ai-seo", name: "Biotech & pharma AI SEO", dir: "src/sublanding/solutions/biotech-ai-seo/", status: "new",
    concept: "A regulatory traffic light: what a page can say pre-approval, on-label, and never, each with its FDA source.",
    q: [["pharma seo", 390, 14, null], ["biotech seo", 260, 8, null], ["medical device seo", 260, 10, null]],
    hook: "Get accurate retrieval of your clinical data, devices and papers in AI answers.",
    build: "Rules: FDA promotional rules (OPDP), no off-label claims, fair balance.",
    truth: "Similar to medtech: this page is pharma and biotech brands, medtech is device and CRO commercial teams.",
    overlap: ["/solutions/medtech-ai-seo"],
  }),
  P({
    phase: 14, route: "/solutions/medtech-ai-seo", name: "Medtech AI SEO", dir: "src/sublanding/solutions/medtech-ai-seo/", status: "new",
    concept: "A 510(k) record turned into a readable product page: clearance number, indication and device class laid out for engines.",
    q: [["medtech marketing agency", 480, 16, 15.68], ["cro marketing agency", 260, 16, null]],
    hook: "Find out whether AI cites your 510(k) clearances and publications.",
    build: "Angle: procurement and trial-sponsor prompts; clearances stated with FDA database links.",
    truth: "The PDF's clinical retrieval audit needs tracking; v1 is the Prompt Kit preset.",
    overlap: ["/solutions/biotech-ai-seo"],
  }),

  /* ---------------- Phase 15 finance ---------------- */
  P({
    phase: 15, route: "/solutions/fintech-ai-seo", name: "Fintech AI SEO", dir: "src/sublanding/solutions/fintech-ai-seo/", status: "new",
    concept: "A B2B buyer's comparison table (fees, limits, licences, integrations) and the answer an engine builds from it, with fictional products.",
    q: [["fintech seo", 1300, 18, 12.17], ["seo for the finance industry", 390, null, 19.21], ["seo for fintech", 320, null, null], ["fintech seo services", 210, null, null]],
    hook: "Win citations when B2B buyers ask AI for financial tools.",
    build: "Angle: B2B buyer prompts (alternatives to a named tool, best for a team size). Yield and rate claims follow the regulators' rules.",
    truth: "Named rivals in examples (Brex, Ramp) are real companies; use fictional ones.",
    overlap: [],
  }),
  P({
    phase: 15, route: "/solutions/insurance-ai-seo", name: "Insurance AI SEO", dir: "src/sublanding/solutions/insurance-ai-seo/", status: "new",
    concept: "A coverage-line selector (cyber, general liability, E&O, workers' comp) with the business-owner questions for each.",
    q: [["insurance seo", 1000, 12, 11.04], ["insurance agency seo", 720, 6, 13.21]],
    hook: "Be the agency AI recommends for commercial coverage questions.",
    build: "Schema: InsuranceAgency. Rules: state insurance advertising rules (NAIC model).",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 15, route: "/solutions/financial-advisor-ai-seo", name: "Financial advisor AI SEO", dir: "src/sublanding/solutions/financial-advisor-ai-seo/", status: "new",
    concept: "Fee-only vs commission as a card pair, and a \"near me\" answer showing which advisor facts it pulls.",
    q: [["financial advisor seo", 480, 18, 22.07], ["cpa seo", 260, 14, 14.34], ["wealth management seo", 140, 15, null]],
    hook: "Get your firm named when clients ask AI for a fee-only fiduciary nearby.",
    build: "Angle: individual advisors and CPAs in local prompts. Rules: SEC Marketing Rule 206(4)-1, FINRA 2210, AICPA advertising.",
    truth: "Similar to wealth management: this page is the advisor or CPA, that one is the firm's brand.",
    overlap: ["/solutions/wealth-management-ai-seo"],
  }),
  P({
    phase: 15, route: "/solutions/wealth-management-ai-seo", name: "Wealth management AI SEO", dir: "src/sublanding/solutions/wealth-management-ai-seo/", status: "new",
    concept: "A liquidity-event timeline (offer, sale, close, after) with the planning questions clients ask at each stage.",
    q: [["wealth management marketing", 390, 5, 10.63]],
    hook: "Be the firm AI quotes on liquidity events and estate planning.",
    build: "Angle: firm-level thought leadership for RIAs and multi-family offices.",
    truth: "Performance and testimonial rules under the SEC Marketing Rule.",
    overlap: ["/solutions/financial-advisor-ai-seo"],
  }),
  P({
    phase: 15, route: "/solutions/private-equity-ai-seo", name: "Private equity AI SEO", dir: "src/sublanding/solutions/private-equity-ai-seo/", status: "new",
    concept: "A founder's exit questions by sector, with the Reg D guardrail pinned beside them.",
    q: [["private equity marketing", 390, 1, 56.9]],
    hook: "Win inbound deal flow when founders ask AI which funds back businesses like theirs.",
    build: "Angle: deal-flow prompts from founders and M&A advisors. Rules: Reg D 506(b) vs 506(c) general solicitation; the page markets to sellers, never to investors.",
    truth: "Fund-marketing rules are the reason this page needs care; say it up front.",
    overlap: [],
  }),

  /* ---------------- Phase 16 multi-location & local ---------------- */
  P({
    phase: 16, route: "/solutions/franchise-ai-seo", name: "Franchise AI SEO", dir: "src/sublanding/solutions/franchise-ai-seo/", status: "new", flag: "call",
    concept: "A table of twelve locations whose facts drift (hours, phone, services), what an AI answer gets wrong, and how brand pages fix it.",
    q: [["franchise seo", 2400, 30, 24.91], ["multi location seo", 1900, 26, 11.46]],
    hook: "Keep every location cited accurately across AI answers.",
    build: "Angle: brand-level content and location facts. Pricing reality: Rankbox is priced per site, not per location.",
    truth: "\"50 to 5,000+ locations\" overstates fit. Your call: how per-site pricing should read to multi-location brands.",
    overlap: ["/use-cases/local-businesses"],
  }),
  P({
    phase: 16, route: "/solutions/automotive-ai-seo", name: "Automotive AI SEO", dir: "src/sublanding/solutions/automotive-ai-seo/", status: "new",
    concept: "A showroom selector (certified pre-owned, EV, service) with the buyer questions and the dealership facts engines need.",
    q: [["automotive seo", 3600, 20, 9.96], ["car dealership seo", 1900, 17, 18.32]],
    hook: "Get your dealership named when buyers ask AI where to buy.",
    build: "Schema: AutoDealer, Vehicle. Prompt map for CPO, EV and service.",
    truth: "Rankbox doesn't handle inventory feeds or VIN-level data; drop those claims.",
    overlap: [],
  }),
  P({
    phase: 16, route: "/solutions/hotel-ai-seo", name: "Hotel AI SEO", dir: "src/sublanding/solutions/hotel-ai-seo/", status: "new",
    concept: "An itinerary-style travel conversation where the hotel appears as a stop, with the amenity facts that put it there.",
    q: [["travel seo", 2400, 22, null], ["hotel seo", 1900, 27, 7.18]],
    hook: "Win direct bookings from conversational travel planning.",
    build: "Schema: Hotel / LodgingBusiness with amenityFeature. Destination-guide topic map.",
    truth: "OTA commission figures need a source.",
    overlap: [],
  }),
  P({
    phase: 16, route: "/solutions/local-ai-seo", name: "Local AI SEO", dir: "src/sublanding/solutions/local-ai-seo/", status: "new",
    concept: "A neighbourhood map with business pins, each opening its industry page.",
    q: [["how ai helps small businesses with local seo", 90, 0, null], ["does ai help with local seo for small businesses", 70, 0, null], ["can ai seo tools help with local seo optimization", 20, 0, null], ["local ai seo", 10, 0, null]],
    hook: "Local generative engine optimization for regional and multi-location services.",
    build: "The hub for local verticals; links down to the industry pages.",
    truth: "Similar to /use-cases/local-businesses and the local-SEO posts; this one is the commercial solution page.",
    overlap: ["/use-cases/local-businesses", "blog: how-ai-helps-small-businesses-with-local-seo", "blog: local-seo-in-chatgpt"],
  }),
  P({
    phase: 16, route: "/solutions/franchise-development-ai-seo", name: "Franchise development AI SEO", dir: "src/sublanding/solutions/franchise-development-ai-seo/", status: "new",
    concept: "The FDD rule laid out plainly: Item 19, and what can and can't be said outside it.",
    q: [["franchise development marketing", 260, 16, 19.9]],
    hook: "Be the brand AI names when investors research franchise opportunities.",
    build: "Rules: the FTC Franchise Rule allows financial performance representations only through Item 19 of the FDD. That rule shapes every page.",
    truth: "The PDF's \"format Item 19 into structured data\" must stay inside the FTC rule; no earnings claims outside the FDD.",
    overlap: ["/solutions/franchise-ai-seo"],
  }),

  /* ---------------- Phase 17 B2B services & education ---------------- */
  P({
    phase: 17, route: "/solutions/manufacturing-ai-seo", name: "Manufacturing AI SEO", dir: "src/sublanding/solutions/manufacturing-ai-seo/", status: "new",
    concept: "An RFQ spec sheet (material, tolerance, certifications, volume) that turns into a quotable capability page.",
    q: [["manufacturing seo", 1900, 31, 33.12], ["industrial seo", 1300, 19, 20.64]],
    hook: "Get your facility cited during AI-assisted RFQ discovery.",
    build: "Angle: capability, tolerance and certification pages (ISO 9001, AS9100) written as plain, quotable facts.",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 17, route: "/solutions/msp-ai-seo", name: "MSP AI SEO", dir: "src/sublanding/solutions/msp-ai-seo/", status: "new",
    concept: "An incident-response timeline after a breach: what a CTO asks AI at each step and the compliance facts that answer.",
    q: [["msp marketing agency", 1000, 16, 14.04], ["msp seo", 720, 18, 11.55]],
    hook: "Why traditional SEO failed MSPs, and how answer engines win contracts.",
    build: "Angle: compliance-led prompts (HIPAA, CMMC, SOC 2) from buyers after an incident or audit.",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 17, route: "/solutions/executive-search-ai-seo", name: "Executive search AI SEO", dir: "src/sublanding/solutions/executive-search-ai-seo/", status: "new",
    concept: "A board briefing document, with the market questions boards ask AI before a search.",
    q: [["executive search marketing", 590, 12, 5.45]],
    hook: "Be the firm AI names for C-suite searches in your niche.",
    build: "Angle: market-intelligence content (compensation, governance) boards and VCs quote.",
    truth: "Compensation data must be sourced.",
    overlap: [],
  }),
  P({
    phase: 17, route: "/solutions/private-school-ai-seo", name: "Private school AI SEO", dir: "src/sublanding/solutions/private-school-ai-seo/", status: "new",
    concept: "An admissions calendar (open house, applications, decisions) with the parent questions in each month.",
    q: [["private school marketing", 480, 18, 6.44], ["private school seo", 170, 1, null], ["independent school marketing", 170, 6, null]],
    hook: "Find out whether ChatGPT names your school when parents ask.",
    build: "Schema: School / EducationalOrganization. Admissions prompt map.",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),

  /* ---------------- Phase 18 real estate ---------------- */
  P({
    phase: 18, route: "/solutions/architecture-ai-seo", name: "Architecture AI SEO", dir: "src/sublanding/solutions/architecture-ai-seo/", status: "new",
    concept: "A project photo with a readable caption layer sliding over it: typology, area, awards and materials as text.",
    q: [["architect seo", 1600, 1, null], ["construction seo", 1600, 27, 12.21]],
    hook: "Turn a visual portfolio into text engines can cite.",
    build: "Angle: project pages with typology, awards and specs as text, because engines can't read the photos.",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 18, route: "/solutions/commercial-real-estate-ai-seo", name: "Commercial real estate AI SEO", dir: "src/sublanding/solutions/commercial-real-estate-ai-seo/", status: "new",
    concept: "An offering memorandum PDF unfolding, section by section, into a structured listing page.",
    q: [["commercial real estate marketing", 720, 7, 5.55]],
    hook: "Make listings and market reports discoverable in AI search.",
    build: "Angle: PDF offering memorandums turned into readable building specs and market pages.",
    truth: "Nothing beyond the house rules.",
    overlap: [],
  }),
  P({
    phase: 18, route: "/solutions/real-estate-ai-seo", name: "Real estate AI SEO", dir: "src/sublanding/solutions/real-estate-ai-seo/", status: "new",
    concept: "A neighbourhood guide with a Fair Housing phrasing check beside each paragraph.",
    q: [["real estate ai seo", 20, 0, null], ["ai seo for real estate", null, null, null]],
    hook: "Be the agent AI recommends in your market.",
    build: "Rules: Fair Housing Act advertising (no preference language), state license disclosures. Schema: RealEstateAgent.",
    truth: "Neighbourhood content must follow Fair Housing; the rules box is required.",
    overlap: [],
  }),

  /* ---------------- Phase 19 off-category alternatives ---------------- */
  P({
    phase: 19, route: "/alternatives/yext", name: "Yext alternative", dir: "src/sublanding/alternatives/yext/", status: "new", flag: "weak",
    concept: "A coverage map in two layers: listing directories, and the pages AI answers quote; shows which layer each tool works on.",
    q: [["yext alternatives", 260, 16, 33.88], ["brightlocal alternatives", 90, 7, 14.28]],
    hook: "The AI search half that listing sync doesn't cover. BrightLocal gets its own section.",
    build: "Honest framing: keep a listings tool for listings; Rankbox for the pages engines quote.",
    truth: "Rankbox doesn't sync listings. \"80% of citations ignored\" needs a source or goes.",
    overlap: [],
  }),
  P({
    phase: 19, route: "/alternatives/podium", name: "Podium alternative", dir: "src/sublanding/alternatives/podium/", status: "new", flag: "weak",
    concept: "A review stream beside an AI summary of the same business: what the summary keeps and what it drops.",
    q: [["podium alternatives", 210, 15, 31.55], ["birdeye alternatives", 110, 17, 25.33]],
    hook: "Beyond star ratings: how AI reads your reputation. Birdeye gets its own section.",
    build: "Honest framing: keep a review tool for reviews, Rankbox for the pages AI summaries draw on. A Birdeye section.",
    truth: "Rankbox doesn't collect reviews or send SMS. No \"sentiment engineering\".",
    overlap: [],
  }),
  P({
    phase: 19, route: "/alternatives/cognism", name: "Cognism alternative", dir: "src/sublanding/alternatives/cognism/", status: "new", flag: "weak",
    concept: "A budget slider between outbound data and inbound content, with what each side buys.",
    q: [["cognism alternatives", 140, 14, 29.14], ["seamless ai alternatives", 90, 6, 20.08]],
    hook: "From cold outbound to inbound from AI search. Seamless.AI gets its own section.",
    build: "Honest framing: a budget shift, not a feature swap. A Seamless.AI section.",
    truth: "Rankbox has no contact data. A visitor wanting a data tool should leave knowing that.",
    overlap: [],
  }),

  /* ---------------- Phase 20 refresh ---------------- */
  P({
    phase: 20, route: "/alternatives/frase", name: "Frase alternative", dir: "src/sublanding/alternatives/frase/", status: "refresh",
    concept: "A conveyor from brief to published: Frase's brief at one end, a cited, live article at the other, each step labelled with who does it.",
    q: [["frase alternatives", 210, 14, null], ["frase alternative", 170, 16, null]],
    hook: "From manual briefs to publishing on autopilot.",
    build: "Rebuilt as its own page at the same route (today it uses the shared /alternatives template): the PDF angle, re-checked prices.",
    truth: "Frase sells AI search tracking now; the matrix must show it.",
    overlap: ["blog: frase-alternatives"],
  }),
  P({
    phase: 20, route: "/alternatives/surfer-seo", name: "Surfer SEO alternative", dir: "src/sublanding/alternatives/surfer-seo/", status: "refresh",
    concept: "Two receipts: the cost of one article on each tool, from both price pages, with content score vs citation readiness beneath.",
    q: [["surfer seo alternatives", 880, 21, 10.72]],
    hook: "Beyond keyword density.",
    build: "Rebuilt as its own page at the same route: a per-article cost comparison from both price pages, re-checked prices.",
    truth: "The PDF's \"$29/article on Surfer\" must come from Surfer's current price page. Surfer tracks AI citations.",
    overlap: ["blog: surfer-seo-alternatives", "/compare/surfer-seo-vs-clearscope"],
  }),
  P({
    phase: 20, route: "/alternatives/jasper", name: "Jasper alternative", dir: "src/sublanding/alternatives/jasper/", status: "refresh",
    concept: "A brand-voice document, then what happens after the draft: sources, score, publish.",
    q: [["jasper alternatives", 260, 26, 8.31], ["jasper ai alternatives", 260, 17, 4.89]],
    hook: "Don't just generate text; get it published and cited.",
    build: "Rebuilt as its own page at the same route: the PDF angle, re-checked prices.",
    truth: "Jasper tracks AI citations now; keep the matrix fair.",
    overlap: ["blog: jasper-alternatives"],
  }),

  /* ---------------- Phase 21 tracking I ---------------- */
  P({
    phase: 21, route: "/solutions/chatgpt-brand-tracking", name: "ChatGPT brand tracking", dir: "src/sublanding/solutions/chatgpt-brand-tracking/", status: "new", flag: "tracking",
    concept: "A ChatGPT answer with competitor names highlighted and your brand's slot shown empty or filled.",
    q: [["chatgpt brand tracking", 90, 3, null]],
    hook: "Is ChatGPT recommending your competitors?",
    build: "Live brand recommendation check.",
    truth: "API answers differ from the ChatGPT app; the page says which one it measures.",
    overlap: ["blog: monitor-brand-mentions-in-chatgpt"],
  }),
  P({
    phase: 21, route: "/tools/perplexity-rank-tracker", name: "Perplexity rank tracker", dir: "src/sublanding/tools/perplexity-rank-tracker/", status: "new", flag: "tracking",
    concept: "Perplexity's numbered source pills as the hero, with your domain located among them.",
    q: [["perplexity rank tracker", 300, 0, null], ["track perplexity rankings", null, null, null]],
    hook: "See whether Perplexity cites you for your buyers' questions.",
    build: "Free check on /tools, full tracking in the product.",
    truth: "Check the Perplexity API's status first; Sonar support changed in September 2026.",
    overlap: ["/ai-seo/perplexity", "blog: track-brand-mentions-in-perplexity"],
  }),
  P({
    phase: 21, route: "/tools/claude-rank-tracker", name: "Claude rank tracker", dir: "src/sublanding/tools/claude-rank-tracker/", status: "new", flag: "tracking",
    concept: "A Claude web-search answer with its source list, and a run-history strip beneath.",
    q: [["claude rank tracker", 140, 0, null]],
    hook: "Check Claude's web-search presence for your category.",
    build: "Free check via the Anthropic API with web search.",
    truth: "\"Claude 3.5/3.7\" is out of date; name current models on the day.",
    overlap: ["/ai-seo/claude"],
  }),
  P({
    phase: 21, route: "/tools/gemini-rank-tracker", name: "Gemini rank tracker", dir: "src/sublanding/tools/gemini-rank-tracker/", status: "new", flag: "tracking",
    concept: "Grounding sources as a stack of cards behind a Gemini answer.",
    q: [["gemini rank tracker", 70, 0, null]],
    hook: "Track the sources Gemini and Google's AI answers ground on.",
    build: "Could ship early as a real free check: the unused Gemini key supports Google Search grounding. Needs your OK on API spend.",
    truth: "Gemini API grounding is not the same as AI Overviews; say which is measured.",
    overlap: ["/ai-seo/gemini"],
  }),
  P({
    phase: 21, route: "/solutions/llm-rank-tracker", name: "LLM rank tracker", dir: "src/sublanding/solutions/llm-rank-tracker/", status: "new", flag: "tracking",
    concept: "A heatmap of prompts × engines × days.",
    q: [["llm rank tracker", 390, 27, 13.74]],
    hook: "Daily automated prompt testing across engines.",
    build: "Multi-model dashboard preview from real runs.",
    truth: "Ships with the tracker.",
    overlap: ["blog: chatgpt-rank-tracker"],
  }),

  /* ---------------- Phase 22 tracking II ---------------- */
  P({
    phase: 22, route: "/solutions/ai-citation-tracker", name: "AI citation tracker", dir: "src/sublanding/solutions/ai-citation-tracker/", status: "new", flag: "tracking",
    concept: "An alert timeline: citations gained, lost and replaced, each with the competitor URL that took the spot.",
    q: [["ai citation tracker", 120, 0, 4.13], ["perplexity citation tracker", null, null, null]],
    hook: "Get an alert when a competitor replaces your link.",
    build: "Citation-loss alerts from tracked runs.",
    truth: "Ships with the tracker.",
    overlap: ["/features/citation-tracking"],
  }),
  P({
    phase: 22, route: "/solutions/ai-overview-tracker", name: "AI Overview tracker", dir: "src/sublanding/solutions/ai-overview-tracker/", status: "new", flag: "tracking",
    concept: "A results page with an AI Overview and its source carousel, tracked over weeks as a strip.",
    q: [["ai search tracker", 1000, null, 14.23], ["ai overview tracking", 880, null, 10.2], ["ai overview checker", 880, null, 4.77], ["ai overview tracker", 590, 23, 10.2], ["how to track ai overviews", 480, null, 11.3]],
    hook: "Know when Google's AI summarises your queries and who it cites.",
    build: "Free check of the top AI Overview citation gaps, then continuous tracking.",
    truth: "Needs a SERP API; \"real-time\" means per run.",
    overlap: ["blog: how-to-show-up-in-google-ai-overviews"],
  }),
  P({
    phase: 22, route: "/solutions/ai-prompt-tracking", name: "AI prompt tracking", dir: "src/sublanding/solutions/ai-prompt-tracking/", status: "new", flag: "tracking",
    concept: "A prompt library grouped by buyer stage, each prompt with its appearance rate.",
    q: [["prompt tracking", 70, 19, 6.6], ["ai prompt tracking", 50, 0, 10.38], ["llm prompt monitoring", 50, 20, null]],
    hook: "Find the questions buyers ask AI about your category, and whether you're in the answer.",
    build: "Prompt simulator: category in, buyer prompts out (real today via the Prompt Kit), then tracked.",
    truth: "Nobody can see what people actually type into ChatGPT; prompts are modelled. Say so.",
    overlap: ["/tools/ai-visibility-prompt-generator", "/tools/ai-question-generator"],
  }),
  P({
    phase: 22, route: "/tools/citation-gap-analysis", name: "Citation gap analysis", dir: "src/sublanding/tools/citation-gap-analysis/", status: "new", flag: "tracking",
    concept: "Three sets of cited sources (yours, competitors', the gap) as a sortable list.",
    q: [["llm citation tracking", 140, 5, null], ["citation gap analysis", 70, 5, null], ["chatgpt citation tracker", 50, 0, null]],
    hook: "The content-gap report for AI search: what's cited for rivals but not for you.",
    build: "Your domain vs three competitors.",
    truth: "Ships with the tracker.",
    overlap: ["blog: how-to-benchmark-ai-citations-against-competitors"],
  }),
  P({
    phase: 22, route: "/tools/ai-source-inspector", name: "AI source inspector", dir: "src/sublanding/tools/ai-source-inspector/", status: "new", flag: "tracking",
    concept: "A source graph: domains as nodes sized by how often engines cite them in your category.",
    q: [["ai visibility tracking", 720, null, 12.42], ["track ai results", 320, 0, null], ["how do you track visibility in llm results", 30, 0, null]],
    hook: "See which sources AI engines lean on for your competitors.",
    build: "Source graph from tracked citations.",
    truth: "Ships with the tracker.",
    overlap: [],
  }),

  /* ---------------- Phase 23 brand & console ---------------- */
  P({
    phase: 23, route: "/solutions/ai-search-console", name: "AI search console", dir: "src/sublanding/solutions/ai-search-console/", status: "new", flag: "tracking",
    concept: "A Search Console-style chart with an AI tab, explaining what Google's generative AI report shows and what it doesn't.",
    q: [["how to track ai mode in google search console", 40, null, null], ["ai search console", 20, 0, null], ["does google search console show ai overviews data", 10, null, null]],
    hook: "The Search Console for AI answers.",
    build: "Listed twice in the PDF (/solutions and /tools); built once, at /solutions.",
    truth: "Search Console rolled out a generative AI report on 2026-08-31, so the PDF's \"GSC hides it all\" is out of date; explain what it shows (impressions only).",
    overlap: [],
  }),
  P({
    phase: 23, route: "/solutions/ai-brand-visibility", name: "AI brand visibility", dir: "src/sublanding/solutions/ai-brand-visibility/", status: "new", flag: "tracking",
    concept: "A share-of-voice ring: your brand against three competitors across engines, from real runs.",
    q: [["llm visibility tool", 1600, null, 19.11], ["ai brand visibility tool", 1600, null, 14.33], ["ai visibility platform", 1600, null, 18.55], ["track chatgpt mentions", 390, 0, null], ["how to monitor if ai answer engines recommend my brand", 320, null, null]],
    hook: "Brand vs top three competitors across ChatGPT, Claude and Perplexity.",
    build: "Live 10-prompt audit.",
    truth: "Close to /solutions/ai-search-visibility; this one is the monitoring side.",
    overlap: ["/solutions/ai-search-visibility"],
  }),
  P({
    phase: 23, route: "/solutions/llm-reputation-management", name: "LLM reputation management", dir: "src/sublanding/solutions/llm-reputation-management/", status: "new", flag: "tracking",
    concept: "A fact sheet with a wrong claim struck through, the source that caused it, and the page that corrects it.",
    q: [["ai reputation management", 320, 26, 14.48], ["llm reputation management", 20, 0, null]],
    hook: "Find and correct what AI says about your brand.",
    build: "Detection needs tracking; the correction half (fact pages, sources) is real today.",
    truth: "No \"automated corrective citation syndication\".",
    overlap: ["blog: how-to-fix-incorrect-brand-facts-in-llm-citations", "blog: brand-sentiment-chatgpt"],
  }),
];
