import {
  ArrowRightLeft,
  Bot,
  Braces,
  ClipboardList,
  FileText,
  Heading,
  HelpCircle,
  Languages,
  Link,
  ListTree,
  Map,
  MessageSquare,
  PencilLine,
  Percent,
  Quote,
  Radar,
  ScrollText,
  Search,
  Share2,
  ShieldCheck,
  Sparkles,
  Tag,
  UserCheck,
  type LucideIcon,
} from "lucide-react";
import type { ToolIcon } from "@/data/tools";

export const TOOL_ICONS: Record<ToolIcon, LucideIcon> = {
  "file-text": FileText,
  bot: Bot,
  "shield-check": ShieldCheck,
  "scroll-text": ScrollText,
  radar: Radar,
  braces: Braces,
  share: Share2,
  languages: Languages,
  map: Map,
  search: Search,
  quote: Quote,
  percent: Percent,
  "list-tree": ListTree,
  link: Link,
  "pencil-line": PencilLine,
  "clipboard-list": ClipboardList,
  "message-square": MessageSquare,
  "help-circle": HelpCircle,
  heading: Heading,
  "arrow-right-left": ArrowRightLeft,
  tag: Tag,
  "user-check": UserCheck,
  sparkles: Sparkles,
};
