import type { GlossaryEntry } from "../types";

export const entry: GlossaryEntry = {
  slug: "ai-overviews",
  metaTitle: "What Are Google AI Overviews? How to Get Cited in Them (2026)",
  metaDescription:
    "Google AI Overviews are Gemini-written summaries atop Google results, linked to their sources. How they pick pages, what they do to clicks, how to track them.",
  keywords: [
    "AI Overviews",
    "Google AI Overviews",
    "what are AI Overviews",
    "how to get into AI Overviews",
    "AI Overviews SEO",
    "SGE",
  ],

  whyItMatters:
    "AI Overviews sit above the results your buyers already see on Google — more than 2.5 billion people use them each month — and when one appears, fewer people click the links below it. For a small team, being one of the few pages an Overview cites now matters as much as the ranking beneath it: Seer Interactive found cited brands earned about 120% more organic clicks per impression than uncited ones.",

  questions: [
    {
      id: "how-to-get-in",
      question: "How do you get into Google AI Overviews?",
      answer:
        "Getting into Google AI Overviews requires a page that is indexed, eligible to show a snippet, and on a site set to Include in Search Console's Search generative AI setting — beyond that, it's won with ordinary SEO and first-hand content that answers the subtopics Google searches.",
      blocks: [
        {
          kind: "requirements",
          items: [
            {
              label: "Indexed",
              status: "required",
              note: "Confirm with URL Inspection in [Google Search Console](/glossary/google-search-console). A page that isn't [indexed](/glossary/indexing) can't be retrieved for any sub-query.",
            },
            {
              label: "Snippet-eligible",
              status: "required",
              note: "No `nosnippet`, and no `max-snippet` value so low it starves the model — both limit what AI Overviews may use. See [snippet controls](/glossary/snippet-controls).",
            },
            {
              label: "Search generative AI set to Include",
              status: "required",
              note: 'Search Console → Settings → Search generative AI. Include is the default, but any owner can change it, and excluded sites "won\'t receive any traffic or impressions from these features."',
            },
            {
              label: "Googlebot allowed everywhere",
              status: "required",
              note: "In robots.txt and at your CDN or firewall. An “AI bot” blocklist that catches Googlebot removes you from Search and its AI features together.",
            },
            {
              label: "Special markup, llms.txt or AI files",
              status: "no-effect",
              note: 'Google: "You don\'t need to create new machine readable files, AI text files, markup, or Markdown." [Schema markup](/glossary/schema-markup) still earns rich results.',
            },
            {
              label: "Google-Extended",
              status: "no-effect",
              note: "Disallowing it opts you out of Gemini training and Gemini-app grounding, not AI Overviews. See [Google-Extended](/glossary/google-extended).",
            },
          ],
        },
      ],
    },
    {
      id: "how-sources-are-chosen",
      question: "How does Google choose AI Overview sources?",
      answer:
        "Google chooses AI Overview sources with its core ranking systems: a Gemini model fans the query out into related searches, answers each from the Search index, and links the pages that support its claims — so a page can be cited for a sub-question it ranks for, not only the typed query.",
      blocks: [
        {
          kind: "p",
          text: 'Google\'s [AI optimization guide](https://developers.google.com/search/docs/fundamentals/ai-optimization-guide) names two techniques: retrieval-augmented generation on top of core ranking, and [query fan-out](/glossary/query-fan-out), "a set of concurrent, related queries generated by the model." Its example turns "how to fix a lawn that\'s full of weeds" into separate searches about herbicides, chemical-free removal and prevention — each with its own winners.',
        },
        {
          kind: "stats",
          items: [
            {
              value: "37.9%",
              label:
                "of pages cited in AI Overviews ranked top 10 for the typed query in March 2026, down from 76.1% in July 2025",
              source: {
                name: "Ahrefs, Mar 2026",
                href: "https://ahrefs.com/blog/ai-overview-citations-top-10/",
              },
            },
            {
              value: "2.5B+",
              label: "monthly users of AI Overviews, announced at Google I/O 2026",
              source: {
                name: "Google, May 2026",
                href: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
              },
            },
          ],
        },
        {
          kind: "p",
          text: 'Ahrefs attributes the fall in top-10 overlap to more aggressive fan-out after Gemini 3 became the default model in January 2026. Google also sets a quality bar: it rewards "non-commodity content" with "unique expert or experienced takes that go beyond common knowledge," and warns that pages made for every fan-out variant to manipulate AI responses count as [scaled content abuse](/glossary/scaled-content-abuse).',
        },
      ],
    },
    {
      id: "clicks",
      question: "Do AI Overviews reduce clicks?",
      answer:
        "AI Overviews reduce clicks for most pages they don't cite: Pew found users clicked a classic result on 8% of visits with an AI summary versus 15% without, while Seer Interactive found cited brands earn about 120% more organic clicks per impression than uncited ones.",
      blocks: [
        {
          kind: "stats",
          items: [
            {
              value: "8% vs 15%",
              label:
                "of visits clicked a classic result with an AI summary present, versus without",
              source: {
                name: "Pew Research, Jul 2025",
                href: "https://www.pewresearch.org/short-reads/2025/07/22/google-users-are-less-likely-to-click-on-links-when-an-ai-summary-appears-in-the-results/",
              },
            },
            {
              value: "−58%",
              label: "click-through for the #1 result when an AI Overview is shown",
              source: {
                name: "Ahrefs, Feb 2026",
                href: "https://ahrefs.com/blog/ai-overviews-reduce-clicks-update/",
              },
            },
            {
              value: "+120%",
              label:
                "organic clicks per impression for brands cited in the Overview versus not cited",
              source: {
                name: "Seer Interactive, Apr 2026",
                href: "https://www.seerinteractive.com/insights/aio-impact-on-google-ctr-2026-update",
              },
            },
          ],
        },
        {
          kind: "p",
          text: "Seer's per-million figures make the gap concrete: about 33,500 organic clicks with no Overview, about 20,700 when the brand is cited and about 9,400 when it isn't. Seer is careful to call this correlation — higher-authority brands are also more likely to be cited. For a small team the lesson holds either way: being cited doesn't restore pre-AI traffic, but it's the difference between a dent and a collapse. See [zero-click search](/glossary/zero-click-search).",
        },
      ],
    },
    {
      id: "how-to-track",
      question: "How do you track AI Overviews?",
      answer:
        "Track AI Overviews with Search Console's Generative AI report, which shows impressions by page, country and device but no clicks, then pair it with a weekly prompt panel for which queries cite you and GA4 for what those visitors do.",
      blocks: [
        {
          kind: "table",
          head: ["Where", "What you get", "What you don't"],
          rows: [
            [
              "Search Console **Generative AI report**",
              "Impressions in AI Overviews and AI Mode by page, country, device and date",
              "Clicks, position, queries",
            ],
            [
              "Search Console **Performance (Web)**",
              "Clicks and impressions, with AI features blended in",
              "A split between AI and classic results",
            ],
            [
              "**GA4**",
              "Sessions and conversions from google.com in Organic Search",
              "Which visits came from an Overview",
            ],
            [
              "**[Prompt tracking](/glossary/prompt-tracking)**",
              "Which queries cite you, and who's cited instead",
              "Google's own impression counts",
            ],
          ],
        },
        {
          kind: "p",
          text: "Two counting rules matter when you read the report. An AI Overview impression counts only once the link is scrolled or expanded into view, and every link inside an Overview is assigned the Overview's single position. GA4's AI Assistant channel won't help here: Google's own AI features are excluded, so those clicks still land in Organic Search.",
        },
      ],
    },
    {
      id: "common-mistakes",
      question: "Common mistakes with AI Overviews",
      answer:
        "The most common AI Overviews mistakes are blocking Google-Extended to leave them, adding schema or llms.txt to enter them, and building one thin page per query variant — none of which does what people expect.",
      blocks: [
        {
          kind: "myths",
          items: [
            {
              myth: "Blocking Google-Extended keeps me out of AI Overviews.",
              reality:
                "It covers Gemini training and Gemini-app grounding. To leave AI Overviews, use the Search Console control, `nosnippet` or `noindex`.",
            },
            {
              myth: "I need special schema or an llms.txt file.",
              reality:
                "Google says there's no special schema.org markup for AI features and that Search ignores llms.txt. Indexing and a snippet are the bar.",
            },
            {
              myth: "Only the #1 result gets cited.",
              reality:
                "In Ahrefs' March 2026 data, 62% of cited pages ranked outside the top 10 for the query. Fan-out spreads citations across sub-questions.",
            },
            {
              myth: "Advice written for SGE still applies.",
              reality:
                "Search Generative Experience was the 2023 Search Labs test that became AI Overviews at Google I/O in May 2024. Models, link placement and controls have all changed since.",
            },
          ],
        },
      ],
    },
  ],

  original: {
    kind: "benchmark",
    name: "The AI Overview Trigger Ladder",
    summary:
      "How likely a Google search is to show an AI summary, by the shape of the query — from Pew Research Center's analysis of 68,879 real searches by 900 US adults in March 2025. Use it to predict which of your target queries will be answered on the results page.",
    items: [
      {
        label: "One or two words",
        value: "8%",
        body: "Short head terms like “CRM software” rarely triggered a summary. Classic ranking and click-through still decide most of the traffic here.",
      },
      {
        label: "All searches",
        value: "18%",
        body: "About one in five searches in the sample produced an AI summary.",
      },
      {
        label: "Written as a full sentence",
        value: "36%",
        body: "Searches phrased as a sentence — the way people describe a problem — triggered summaries twice as often as average.",
      },
      {
        label: "Ten words or more",
        value: "53%",
        body: "Long, specific queries, the [long tail](/glossary/long-tail-keywords), showed a summary more often than not.",
      },
      {
        label: "Starts with a question word",
        value: "60%",
        body: "Searches beginning with who, what, when or why were the most likely to get an AI answer — the queries where being cited matters most.",
      },
    ],
    outcome:
      "The values are from March 2025, before Gemini 3 and the 2026 expansions, so treat them as historical and spot-check your own queries in a private window. The direction is what to plan around: the more your buyers phrase a query as a question, the more likely the answer is written for them — and the more your plan should aim at being cited, not only at ranking.",
  },

  related: [
    "ai-mode",
    "zero-click-search",
    "featured-snippet",
    "query-fan-out",
    "snippet-controls",
    "google-extended",
  ],
  product: {
    feature: "citation-tracking",
    pitch:
      "Rankbox tracks where your brand shows up in Google AI Overviews — alongside ChatGPT, Perplexity and Claude — for the prompts your buyers ask, and shows which article earned each citation, the view Search Console's click-less report doesn't give you.",
  },
  further: [
    {
      title: "Google AI Overviews & AI Mode SEO",
      href: "/ai-seo/google-ai-overviews",
      description:
        "The technical guide: eligibility switches, snippet controls, the Search Console AI report and the citation data.",
    },
    {
      title: "How to show up in Google AI Overviews",
      href: "/blog/how-to-show-up-in-google-ai-overviews",
      description: "The step-by-step content playbook for earning AI Overview citations.",
    },
  ],
  sources: [
    {
      title: "AI features and your website",
      publisher: "Google Search Central",
      href: "https://developers.google.com/search/docs/appearance/ai-features",
    },
    {
      title: "Optimizing your website for generative AI features",
      publisher: "Google Search Central",
      href: "https://developers.google.com/search/docs/fundamentals/ai-optimization-guide",
    },
    {
      title: "Search generative AI control",
      publisher: "Search Console Help",
      href: "https://support.google.com/webmasters/answer/16908024",
    },
    {
      title: "Introducing Search generative AI performance reports",
      publisher: "Google Search Central Blog",
      href: "https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports",
    },
    {
      title: "How Search Console counts position, clicks and impressions",
      publisher: "Search Console Help",
      href: "https://support.google.com/webmasters/answer/7042828",
    },
    {
      title: "Google users are less likely to click on links when an AI summary appears",
      publisher: "Pew Research Center",
      href: "https://www.pewresearch.org/short-reads/2025/07/22/google-users-are-less-likely-to-click-on-links-when-an-ai-summary-appears-in-the-results/",
    },
    {
      title: "How many AI Overview citations rank in the top 10?",
      publisher: "Ahrefs",
      href: "https://ahrefs.com/blog/ai-overview-citations-top-10/",
    },
    {
      title: "AI Overviews reduce clicks by 58%",
      publisher: "Ahrefs",
      href: "https://ahrefs.com/blog/ai-overviews-reduce-clicks-update/",
    },
    {
      title: "AIO impact on Google CTR: 2026 update",
      publisher: "Seer Interactive",
      href: "https://www.seerinteractive.com/insights/aio-impact-on-google-ctr-2026-update",
    },
    {
      title: "Gemini 3 in AI Overviews and follow-ups in AI Mode",
      publisher: "Google",
      href: "https://blog.google/products-and-platforms/products/search/ai-mode-ai-overviews-updates/",
    },
    {
      title: "Google I/O 2024: New generative AI experiences in Search",
      publisher: "Google",
      href: "https://blog.google/products-and-platforms/products/search/generative-ai-google-search-may-2024/",
    },
  ],
};
