/**
 * One-query standalone posts, each with the category ("hub") post it links up
 * to. They're shorter than the hubs, and each hub links back down to them.
 *
 * ai-search-posts.test.ts holds both ends to that, and the blog scheduler
 * (scripts/blog-schedule.ts) publishes a hub before any of its standalones.
 */
export const STANDALONES: Record<string, string> = {
  "applebot-user-agent": "applebot-apple-intelligence-search",
  "ai-crawler-robots-txt": "ai-crawler-robots-txt-guide",
  "block-ai-bots-cloudflare": "cloudflare-ai-bot-management",
  "cloudflare-ai-bots": "cloudflare-ai-bot-management",
  "prerender-seo": "dynamic-rendering-prerendering-ai-crawlers",
  "dynamic-rendering-seo": "dynamic-rendering-prerendering-ai-crawlers",
  "what-is-edge-seo": "edge-seo-for-ai-cloudflare-workers",
  "edge-seo": "edge-seo-for-ai-cloudflare-workers",
  "how-user-search-intent-evolves-with-conversational-ai": "death-of-10-blue-links",
  "how-to-measure-roi-from-zero-click-searches": "headless-brand-zero-click",
  "zero-click-searches": "headless-brand-zero-click",
  "does-chatgpt-search-have-paid-ads": "chatgpt-search-ads-conversational-ppc",
  "chatgpt-search-ads": "chatgpt-search-ads-conversational-ppc",
  "how-saas-companies-use-ai-for-seo-content-creation":
    "prompt-zero-purchase-ai-agents-buy-software",
  "what-are-ai-powered-seo-agents": "agentic-seo-autonomous-ai-buyers",
  "ai-powered-seo-agents": "agentic-seo-autonomous-ai-buyers",
  "what-is-agentic-seo": "agentic-seo-autonomous-ai-buyers",
  "how-does-prompt-injection-work": "indirect-prompt-injection-black-hat-geo",
  "what-is-prompt-injection": "indirect-prompt-injection-black-hat-geo",
  "indirect-prompt-injection": "indirect-prompt-injection-black-hat-geo",
  "what-is-multimodal-search": "multimodal-geo",
  "multimodal-seo": "multimodal-geo",
  "does-podcast-image-help-seo": "podcast-transcripts-ai-search-citations",
  "podcast-seo": "podcast-transcripts-ai-search-citations",
  "how-can-a-podcast-increase-seo": "podcast-transcripts-ai-search-citations",
  "seo-newsletters": "substack-arbitrage-llm-knowledge",
  "substack-seo": "substack-arbitrage-llm-knowledge",
  "is-substack-good-for-seo": "substack-arbitrage-llm-knowledge",
  "open-source-seo-tools": "github-readme-ai-seo",
  "github-pages-seo": "github-readme-ai-seo",
  "github-seo": "github-readme-ai-seo",
  "ai-link-building": "link-building-ai-visibility-co-citation",
  "does-link-building-help-ai-visibility": "link-building-ai-visibility-co-citation",
  "how-chatgpt-search-decides-citations": "apple-intelligence-siri-chatgpt",
  "what-does-apple-intelligence-do": "apple-intelligence-siri-chatgpt",
  "how-to-get-cited-by-chatgpt-as-a-local-business": "local-seo-in-chatgpt",
  "how-ai-helps-small-businesses-with-local-seo": "local-seo-in-chatgpt",
  "how-to-rank-in-ai-search-results": "reddit-in-ai-search",
  "how-to-use-reddit-for-seo": "reddit-in-ai-search",
  "best-chatgpt-seo-software": "chatgpt-ranking-factors-ai-search-placement",
  "chatgpt-ranking-factors": "chatgpt-ranking-factors-ai-search-placement",
  "voice-search-optimization-2026": "voice-search-ai-powered",
  "how-search-intent-is-evolving-with-conversational-ai":
    "ai-search-intent-conversational-buyer-stages",
  "what-is-ai-mode-in-google": "google-ai-mode-vs-traditional-search",
  "what-is-google-ai-mode": "google-ai-mode-vs-traditional-search",
  "how-often-to-update-content-for-ai-seo": "freshness-factor-ai-search",
  "content-freshness-seo": "freshness-factor-ai-search",
  "author-bio-seo": "do-author-bios-help-ai-search-visibility",
  "do-author-bios-help-seo": "do-author-bios-help-ai-search-visibility",
  "ai-seo-checklist": "ai-seo-checklist-pre-publish-audit",
  "evaluate-geo-tool-before-purchasing": "aeo-audit",
  "geo-tools-list": "aeo-audit",
  "claude-seo-tool": "claude-for-seo-audits",
  "how-to-use-claude-for-seo-audits": "claude-for-seo-audits",
  "entity-authority-seo": "entity-authority-in-the-ai-era",
  "what-is-entity-authority-in-seo": "entity-authority-in-the-ai-era",
  "how-to-compare-generative-engine-optimization-software": "comparison-page-formula",
  "are-automated-blog-posts-effective-for-seo": "synthetic-content-saturation-model-collapse",
  "how-to-write-blog-posts-for-ai-citation": "reverse-prompt-playbook",
  "how-to-optimize-content-for-llms": "optimize-content-for-llms-writing-for-machines",
  "seo-knowledge-graph": "knowledge-graph-for-ai",
  "knowledge-graph-search-api": "knowledge-graph-for-ai",
  "what-is-a-knowledge-graph-in-seo": "knowledge-graph-for-ai",
  "how-ai-models-rank-brands-in-search-results": "semantic-drift-ai-memory-reset",
  "how-does-rag-reduce-hallucinations": "hallucination-by-omission-pricing-page",
  "how-to-monitor-brand-mentions-in-ai-generated-responses": "defensive-geo",
  "how-to-fix-incorrect-brand-facts-in-llm-citations": "fix-incorrect-brand-facts-in-ai-answers",
  "how-to-track-competitor-rankings-in-ai-search":
    "how-to-benchmark-ai-citations-against-competitors",
  "is-it-possible-to-track-brand-mentions-in-ai-search":
    "is-it-possible-to-track-brand-mentions-in-ai-answers",
  "see-if-ai-mentions-your-brand-places-to-look": "how-to-see-if-ai-mentions-your-brand",
  "track-brand-mentions-in-ai-search-free-and-paid": "how-to-track-brand-mentions-in-ai-search",
  "how-to-benchmark-website-performance-in-ai-search": "geo-metrics-framework",
  "what-is-generative-engine-optimization": "geo-metrics-framework",
  "perplexitybot-user-agent": "ai-crawler-directory",
  "how-to-track-gptbot-and-claudebot": "ai-crawler-directory",
  "what-is-oai-searchbot": "ai-crawler-directory",
  "why-is-cloudflare-blocking-chatgpt": "cloudflare-challenge-trap",
  "cloudflare-blocking-chatgpt": "cloudflare-challenge-trap",
  "how-to-use-bing-webmaster-tools-for-seo": "bing-webmaster-tools-ai-indexing-guide",
  "does-bing-webmaster-tools-help-google-indexing": "bing-webmaster-tools-ai-indexing-guide",
  "will-llms-txt-help-your-seo": "how-to-get-indexed-by-llms-with-llms-txt",
  "how-to-get-indexed-by-llm-through-llms-txt": "how-to-get-indexed-by-llms-with-llms-txt",
  "what-is-an-llms-txt-file": "state-of-llms-txt-adoption",
  "llms-txt-standard": "state-of-llms-txt-adoption",
  "how-to-track-ai-referral-traffic-in-ga4": "how-to-measure-ai-referral-traffic-in-ga4",
  "chatgpt-traffic-analysis": "how-to-measure-ai-referral-traffic-in-ga4",
  "how-to-benchmark-ai-search-performance": "ai-bot-crawler-census",
  "how-does-ai-search-interpret-user-intent": "vector-distance-vs-keyword-density",
  "how-ai-search-uses-user-intent-and-context": "vector-distance-vs-keyword-density",
};
