import type { EngineGuide } from "../types";

export const googleAiOverviews: EngineGuide = {
  slug: "google-ai-overviews",
  metaTitle: "Google AI Overviews & AI Mode SEO: The Technical Guide (2026)",
  metaDescription:
    "How Google AI Overviews and AI Mode pick sources: query fan-out, eligibility, the new Search Console AI control and report, snippet controls, and what the citation data shows.",
  keywords: [
    "AI Overviews SEO",
    "AI Mode SEO",
    "Google AI Overviews optimization",
    "how to appear in AI Overviews",
    "Search generative AI control",
    "query fan-out",
  ],
  headline: { lead: "Google AI Overviews & AI Mode SEO:", accent: "the technical guide" },
  subhead:
    "How Google grounds its AI answers in the Search index, the three switches that decide whether you're eligible, what the 2026 citation data shows, and how to measure it now that Search Console reports on it.",

  shortAnswer:
    "To be cited in Google AI Overviews and AI Mode, a page must be indexed, eligible to show a snippet, and on a site set to **Include** in Search Console's new Search generative AI setting. Nothing else is required: Google grounds both features in its core ranking systems and uses **query fan-out** to search related subtopics, so you win citations with helpful, non-commodity content that answers those subtopics — not with special files or markup.",

  takeaways: [
    'There is no AI-specific markup, file or schema. Google says optimizing for AI features "is still SEO."',
    "Eligibility has three switches: indexed, snippet-eligible, and **Include** in Search Console → Settings → Search generative AI.",
    "`Google-Extended` does **not** remove you from AI Overviews. It only governs Gemini training and grounding outside Search.",
    "Google answers by fanning one query out into several. In Ahrefs' March 2026 data only 37.9% of cited pages ranked top 10 for the typed query.",
    "Search Console's Generative AI report shows impressions by page — but no clicks, so pair it with a citation tracker.",
    "Being cited matters: Seer Interactive found cited brands earn about 120% more organic clicks per impression than uncited ones.",
  ],

  facts: [
    { label: "Monthly AI Overviews users (May 2026)", value: "2.5B+" },
    { label: "Monthly AI Mode users (May 2026)", value: "1B+" },
    { label: "The crawler that governs it", value: "Googlebot", mono: true },
    { label: "Where to measure it", value: "Search Console AI report" },
  ],

  preview: {
    prompt: "best project management software for a small startup",
    status: "AI Overview",
    answer:
      "For small startup teams, **Plannora** is a common pick: simple boards, built-in automations and a free tier for up to five people. Teams that live in spreadsheets often prefer Loopcraft's table view.",
    sources: [
      { domain: "plannora.io", title: "Plannora pricing: free for teams of up to 5" },
      { domain: "stackreview.co", title: "Best project management tools for startups (2026)" },
      { domain: "founderforum.net", title: "What PM tool does your 5-person team use?" },
    ],
  },

  profile: {
    retrieval: "Google's Search index, through its core ranking systems and query fan-out",
    searchCrawler: "Googlebot",
    trainingCrawler: "Google-Extended — no effect on AI Overviews",
    rendersJs: "Yes — Google renders JavaScript that isn't blocked",
    referrer: "google.com (Organic Search)",
    citationStyle: "Inline links beside the claim, link cards, a further-exploration list",
    biggestLever: "Non-commodity content covering the subtopics Google fans out to",
  },

  sections: [
    {
      id: "how-it-works",
      title: "How AI Overviews and AI Mode choose their sources",
      blocks: [
        {
          kind: "p",
          text: 'Both features are built on Search itself. Google\'s [AI optimization guide](https://developers.google.com/search/docs/fundamentals/ai-optimization-guide) says they "are rooted in our core Search ranking and quality systems" and names two techniques: **retrieval-augmented generation**, where core ranking retrieves pages from the Search index and a Gemini model writes an answer linking to them, and **query fan-out**, "a set of concurrent, related queries generated by the model."',
        },
        {
          kind: "p",
          text: 'Fan-out is the part that changes how you plan content. Google\'s own example: "how to fix a lawn that\'s full of weeds" becomes "best herbicides for lawns," "remove weeds without chemicals" and "how to prevent weeds in lawn." Each of those is a separate search with its own winners, and each can contribute a link to the final answer.',
        },
        {
          kind: "pipeline",
          steps: [
            {
              title: "Google decides whether an AI answer adds anything",
              body: 'AI Overviews are "only shown when our systems determine that it is additive to classic Search, and as such, often don\'t trigger." Question-shaped and long queries trigger them far more often: Pew saw summaries on 60% of question queries against 8% of one- or two-word ones.',
            },
            {
              title: "The query fans out into subtopics",
              body: 'The model issues several related searches at once, across subtopics and data sources. AI Mode\'s Deep Search can issue "hundreds of searches" for a single report.',
              lever:
                "Cover the sub-questions around your topic in depth — as a strong page or a tight cluster, not one thin page per variant.",
            },
            {
              title: "Core ranking retrieves candidate pages",
              body: "Each fan-out query is answered from the Search index by the normal ranking and quality systems. Pages that are not indexed, or not allowed a snippet, never enter the pool.",
              lever: "Be indexed, snippet-eligible and set to Include in Search Console.",
            },
            {
              title: "Gemini writes a grounded answer",
              body: 'Gemini 3 has been the default model for AI Overviews since January 2026; Gemini 3.5 Flash has powered AI Mode since I/O in May 2026. Google notes the two "may use different models and techniques, so the set of responses and links they show will vary."',
              lever:
                "Give it passages worth grounding on: specific, first-hand, clearly structured.",
            },
            {
              title: "Links are attached to the claims they support",
              body: 'Since May 2026 Google places more inline links next to the generated text, previews site names on hover, labels links from publications the user subscribes to, adds a "further exploration" list of in-depth articles, and surfaces forum and social perspectives with the creator attributed.',
            },
            {
              title: "AI Mode keeps the conversation going",
              body: "Follow-up questions — including ones started from an AI Overview — continue in AI Mode with context carried over. In Search Console, each follow-up counts as a new query.",
            },
          ],
        },
        {
          kind: "stats",
          items: [
            {
              value: "2.5B+",
              label: "monthly users of AI Overviews, announced at Google I/O 2026",
              source: {
                name: "Google, May 2026",
                href: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
              },
            },
            {
              value: "1B+",
              label: 'monthly users of AI Mode, where queries "more than doubled every quarter"',
              source: {
                name: "Alphabet Q2 2026 earnings",
                href: "https://blog.google/company-news/inside-google/message-ceo/alphabet-earnings-q2-2026/",
              },
            },
            {
              value: "13.7%",
              label: "of the time, AI Mode and AI Overviews cite the same URL for a query",
              source: {
                name: "Ahrefs, Dec 2025",
                href: "https://ahrefs.com/blog/ai-overviews-vs-ai-mode/",
              },
            },
          ],
        },
        {
          kind: "callout",
          tone: "note",
          title: "AI Overviews and AI Mode are now one experience",
          text: 'At I/O 2026 Google merged the two into "one seamless Search experience," live worldwide on desktop and mobile. They still pick sources differently — AI Mode answers run about four times longer and show more domains — but eligibility, controls and reporting are shared, so you optimize for both at once.',
        },
      ],
    },
    {
      id: "eligibility",
      title: "Eligibility: the switches that decide if you can be cited",
      blocks: [
        {
          kind: "p",
          text: 'Google\'s [AI features documentation](https://developers.google.com/search/docs/appearance/ai-features) sets one bar: a page must be "indexed and eligible to be shown in Google Search with a snippet." It adds that "there are no additional technical requirements." The 2026 optimization guide adds one more: "a site must be included in Search generative AI features in Search Console to be eligible." Include is the default — but check it, because anyone with owner access can change it.',
        },
        {
          kind: "requirements",
          items: [
            {
              label: "Indexed",
              status: "required",
              note: "Confirm with Search Console's URL Inspection. A page Google hasn't indexed cannot be retrieved for any fan-out query. Indexing \"isn't guaranteed,\" so internal links and sitemaps still matter.",
            },
            {
              label: "Snippet-eligible",
              status: "required",
              note: "No `nosnippet`, and no `max-snippet` value so low it starves the model. Both explicitly limit what AI Overviews and AI Mode may use as input.",
            },
            {
              label: "Included in Search generative AI",
              status: "required",
              note: 'Search Console → Settings → Search generative AI must read **Include** (or inherit Include from a parent property). Excluded sites "won\'t receive any traffic or impressions from these features."',
            },
            {
              label: "Googlebot allowed — everywhere",
              status: "required",
              note: 'In robots.txt **and** at your CDN, WAF and bot-management layer. Google calls this out: an "AI bot" blocklist that catches Googlebot takes you out of Search and its AI features together.',
            },
          ],
        },
      ],
    },
    {
      id: "controls",
      title: "Crawlers and controls: what each one actually does",
      blocks: [
        {
          kind: "p",
          text: 'There is no separate AI crawler for Search. Google is explicit: "AI is built into Search and integral to how Search functions, which is why robots.txt directives for Googlebot is the control." The token most people reach for, `Google-Extended`, does something else entirely.',
        },
        {
          kind: "crawlers",
          bots: [
            {
              token: "Googlebot",
              role: "search",
              purpose:
                "Crawls for Google Search, including AI Overviews and AI Mode. Blocking it removes you from Search altogether.",
              robots: "yes",
              advice: "allow",
            },
            {
              token: "Google-Extended",
              role: "training",
              purpose:
                'A robots.txt token (not a separate crawler) for training future Gemini models and for grounding in the Gemini app and Vertex AI. Google: it "does not impact a site\'s inclusion in Google Search nor is it used as a ranking signal."',
              robots: "yes",
              advice: "your-call",
            },
          ],
        },
        {
          kind: "p",
          text: "So a robots.txt that opts out of Gemini training while staying fully eligible for AI Overviews looks like this:",
        },
        {
          kind: "code",
          lang: "robots.txt",
          code: "# Search, AI Overviews and AI Mode — never block this\nUser-agent: Googlebot\nAllow: /\n\n# Optional: opt out of Gemini training and Gemini-app grounding.\n# Has no effect on AI Overviews or AI Mode.\nUser-agent: Google-Extended\nDisallow: /",
        },
        {
          kind: "h3",
          text: "Every control, and what it really switches off",
        },
        {
          kind: "table",
          head: ["Control", "AI Overviews & AI Mode", "Classic results", "Model training"],
          rows: [
            [
              "Search Console → **Search generative AI: Exclude**",
              "Removed (also Discover AI)",
              "Unaffected",
              "Unaffected",
            ],
            ["`nosnippet`", "Not used as input", "No snippet shown", "Unaffected"],
            ["`max-snippet:[n]`", "Input capped at n characters", "Snippet capped", "Unaffected"],
            [
              "`data-nosnippet` on an element",
              "That passage excluded",
              "Passage excluded",
              "Unaffected",
            ],
            ["`noindex`", "Removed", "Removed", "Unaffected"],
            ["`Google-Extended` disallowed", "**Unaffected**", "Unaffected", "Opted out"],
          ],
        },
        {
          kind: "p",
          text: 'The Search Console control, rolled out worldwide on 31 August 2026, is the only one built for this job. It works per property — domain, subdomain or URL-prefix, so a URL-prefix property can scope it to one folder — takes effect in "a few days," and Google says it is "not used as a ranking or inclusion signal affecting other parts of Search." It does not touch training (that\'s `Google-Extended`) or Merchant Center and Ads participation.',
        },
        {
          kind: "p",
          text: "To keep one passage out of AI answers without losing the page — a price you don't want quoted out of context, say — wrap it in `data-nosnippet`:",
        },
        {
          kind: "code",
          lang: "html",
          code: "<p>Plans start at $29 a month.</p>\n<div data-nosnippet>\n  Enterprise pricing is negotiated per contract.\n</div>",
        },
        {
          kind: "callout",
          tone: "warning",
          title: "The UK is getting more controls",
          text: "In June 2026 the UK's Competition and Markets Authority imposed a conduct requirement on Google covering an opt-out from AI features while staying in Search, an opt-out from fine-tuning, and clearer attribution. Google has until about March 2027 to comply. Page-level mechanics have been reported but aren't documented by Google yet.",
        },
      ],
    },
    {
      id: "technical",
      title: "Technical requirements, and the things that don't matter",
      blocks: [
        {
          kind: "p",
          text: "Because AI features sit on Search, the technical bar is Search's bar. The useful work is making sure Google can render, understand and prefer your page — and not wasting weeks on files and markup Google has said it ignores.",
        },
        {
          kind: "requirements",
          items: [
            {
              label: "JavaScript rendering",
              status: "helps",
              note: "\"Google is able to process content within JavaScript as long as it isn't blocked.\" Don't block JS or CSS in robots.txt, and check the rendered HTML in URL Inspection. Server-rendered text is still safest — and it's what every other engine needs.",
            },
            {
              label: "Key content in the first 2 MB",
              status: "required",
              note: 'Googlebot fetches the first 2 MB of a URL\'s HTML; anything after the cut-off is "not fetched… not rendered… not indexed." Put the title, canonical and main content early, and avoid inlining huge scripts or base64 images.',
            },
            {
              label: "Page experience",
              status: "helps",
              note: "Works on every device, loads quickly, and makes the main content clearly distinguishable from navigation and ads.",
            },
            {
              label: "Internal links & duplicates",
              status: "helps",
              note: 'Make deep pages "easily findable through internal links," and consolidate duplicates with canonicals so ranking signals aren\'t split.',
            },
            {
              label: "Original images & video",
              status: "helps",
              note: "Google's guide recommends high-quality media. YouTube was the single most-cited domain in AI Overviews in Ahrefs' 2026 data, at 5.6% of cited URLs.",
            },
            {
              label: "Structured data",
              status: "no-effect",
              note: 'Not required for AI features and there is "no special schema.org structured data." Keep it for rich results — and make sure it matches the visible text.',
            },
            {
              label: "llms.txt & AI text files",
              status: "no-effect",
              note: '"You don\'t need to create new machine readable files, AI text files, or markup." Google Search ignores llms.txt; it neither helps nor hurts here.',
            },
            {
              label: "Chunking & rewriting for AI",
              status: "no-effect",
              note: 'Google says there is no need to chunk content or rewrite it for AI, and "no ideal page length." Write clear sections for people.',
            },
            {
              label: "Merchant Center feed",
              status: "helps",
              note: "For shopping answers. AI Mode shops from the Shopping Graph (60B+ listings), so keep prices, shipping, returns and attributes current. Agentic checkout is live for select US merchants.",
            },
            {
              label: "Google Business Profile",
              status: "helps",
              note: "For local answers — hours, categories, reviews. AI Mode's agentic booking for local services launched in the US in summer 2026.",
            },
          ],
        },
      ],
    },
    {
      id: "what-gets-cited",
      title: "What gets cited: ranking, fan-out and non-commodity content",
      blocks: [
        {
          kind: "p",
          text: "Ranking still matters — it's how pages enter the pool — but the typed query is no longer the only race. Fan-out means your page can be cited for a sub-question you rank for even when you're nowhere for the original query. The data shows the share of citations coming from outside the top 10 growing fast.",
        },
        {
          kind: "table",
          head: ["Study", "Sample", "Cited pages in the top 10"],
          rows: [
            [
              "[Ahrefs, Jul 2025](https://ahrefs.com/blog/ai-overview-citations-top-10/)",
              "1M AI Overviews, 1.9M citations",
              "76.1%",
            ],
            [
              "[Ahrefs, Mar 2026](https://ahrefs.com/blog/ai-overview-citations-top-10/)",
              "863K SERPs, 4M cited URLs",
              "37.9% (31.0% ranked beyond 100)",
            ],
            [
              "[BrightEdge, Sep 2025](https://www.brightedge.com/resources/weekly-ai-search-insights/rank-overlap-after-16-months-of-aio)",
              "9 industries, 16 months",
              "54.5% rank organically (any position)",
            ],
          ],
        },
        {
          kind: "p",
          text: "Ahrefs attributes the fall to more aggressive fan-out after Gemini 3 arrived. What that means in practice: the most reliable way into an answer is to be the best result for one of its sub-questions.",
        },
        {
          kind: "signals",
          items: [
            {
              title: "Core ranking and quality",
              body: "Grounding runs on the same ranking and quality systems as Search. Helpful, reliable, people-first content and E-E-A-T apply unchanged.",
              evidence: "official",
            },
            {
              title: "Non-commodity content",
              body: 'Google contrasts "7 Tips for First-Time Homebuyers" with "Why We Waived the Inspection & Saved Money." First-hand experience and original data are what a generic answer can\'t supply.',
              evidence: "official",
            },
            {
              title: "Subtopic coverage",
              body: "Pages that win a fan-out sub-query get cited even when they don't rank for the head term — the likely driver of the 76% → 38% shift.",
              evidence: "observed",
            },
            {
              title: "Video and forums",
              body: 'YouTube leads cited domains, and since May 2026 Google surfaces forum and social "perspectives" with attribution. Being discussed off-site is a second path in.',
              evidence: "observed",
            },
            {
              title: "Clear sections",
              body: "Google recommends clear headings and sections. It doesn't endorse answer-first formatting specifically — we find direct openings get lifted more, but that's practitioner evidence.",
              evidence: "our-read",
            },
            {
              title: "Per-variant pages backfire",
              body: 'Creating pages for every fan-out variant "primarily to manipulate generative AI responses" is, per Google, scaled content abuse. Build depth, not doorways.',
              evidence: "official",
            },
          ],
        },
      ],
    },
    {
      id: "clicks",
      title: "What AI Overviews do to your clicks",
      blocks: [
        {
          kind: "p",
          text: "The honest framing: for uncited pages, AI Overviews cost clicks. For cited ones, they cost less — and sometimes pay. That makes being cited as much a defensive move as a growth one.",
        },
        {
          kind: "stats",
          items: [
            {
              value: "8% vs 15%",
              label:
                "of visits clicked a classic result with an AI summary present, versus without",
              source: {
                name: "Pew Research, Jul 2025",
                href: "https://www.pewresearch.org/short-reads/2025/07/22/google-users-are-less-likely-to-click-on-links-when-an-ai-summary-appears-in-the-results/",
              },
            },
            {
              value: "−58%",
              label: "click-through for the #1 result when an AI Overview is shown",
              source: {
                name: "Ahrefs, Feb 2026",
                href: "https://ahrefs.com/blog/ai-overviews-reduce-clicks-update/",
              },
            },
            {
              value: "+120%",
              label:
                "organic clicks per impression for brands cited in the Overview versus not cited",
              source: {
                name: "Seer Interactive, Apr 2026",
                href: "https://www.seerinteractive.com/insights/aio-impact-on-google-ctr-2026-update",
              },
            },
          ],
        },
        {
          kind: "p",
          text: "Seer's numbers put it most concretely: per million informational impressions, about 33,500 clicks with no AI Overview, about 20,700 when the brand is cited, and about 9,400 when it isn't. Seer notes this is correlation, not proof. Google's own position is that AI-feature clicks are \"higher quality,\" though it hasn't published data for that.",
        },
      ],
    },
    {
      id: "measurement",
      title: "Measuring AI Overviews and AI Mode",
      blocks: [
        {
          kind: "p",
          text: "Measurement changed more in 2026 than anything else. On 3 June Google launched the [Search generative AI performance report](https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports), rolled out worldwide by 31 August. It's the first first-party view of AI visibility — with one big gap.",
        },
        {
          kind: "table",
          head: ["Where", "What you get", "What you don't"],
          rows: [
            [
              "Search Console **Generative AI report**",
              "Impressions by page, country, device and date — hourly to monthly",
              "Clicks, position, queries",
            ],
            [
              "Search Console **Performance (Web)**",
              "Clicks and impressions, with AI features blended in",
              "Any split between AI and classic results",
            ],
            [
              "**GA4**",
              "Sessions and conversions from google.com in Organic Search",
              "Which visits came from an AI answer",
            ],
            [
              "**Citation tracker**",
              "Which prompts cite you, and who's cited instead",
              "Google's own impression counts",
            ],
          ],
        },
        {
          kind: "list",
          items: [
            "**Impressions** count when a link to your site is shown in an AI feature — for AI Overviews, only once it's scrolled or expanded into view. Two links in one answer count as one impression in the property chart.",
            "**Position:** an AI Overview occupies one position, and every link in it is assigned that position. In AI Mode, positions count as in regular Search.",
            "**Follow-ups** in AI Mode are logged as new queries.",
            "**GA4:** a new AI Assistant default channel (May 2026) groups assistants such as ChatGPT, Gemini and Copilot. Google's own AI features are excluded — those clicks still land in Organic Search from google.com.",
          ],
        },
        {
          kind: "p",
          text: "The practical setup: watch the AI report for which pages gain impressions, check those pages' engagement and conversions in GA4, and run a fixed weekly prompt panel for the citations Search Console can't show. Google's own caveat applies to every tool, ours included: \"no third-party tool has access to our internal ranking or AI systems.\"",
        },
      ],
    },
    {
      id: "myths",
      title: "Myths worth dropping",
      blocks: [
        {
          kind: "myths",
          items: [
            {
              myth: "You need llms.txt, an AI file or special schema to appear in AI Overviews.",
              reality:
                "Google says no new files, AI text files or special structured data are needed, and it ignores llms.txt. The eligibility bar is indexing and a snippet.",
            },
            {
              myth: "Blocking Google-Extended keeps you out of AI Overviews.",
              reality:
                "It doesn't. `Google-Extended` covers Gemini training and Gemini-app grounding. To leave AI Overviews use the Search Console control, `nosnippet` or `noindex`.",
            },
            {
              myth: "Only the #1 result gets cited — or ranking #1 guarantees it.",
              reality:
                "In Ahrefs' 2026 data 62% of cited pages ranked outside the top 10 for the query. Fan-out spreads citations across sub-questions.",
            },
            {
              myth: "GEO is a separate discipline with its own tricks.",
              reality:
                'Google: "optimizing for generative AI search is optimizing for the search experience, and thus still SEO." Inauthentic mentions and per-variant pages don\'t help and can breach spam policy.',
            },
          ],
        },
      ],
    },
  ],

  checklist: [
    {
      id: "sc-include",
      title: "Confirm the Search generative AI setting is Include",
      detail:
        "Search Console → Settings → Search generative AI. Check every property, including inheritance from parent domain properties.",
      impact: "high",
    },
    {
      id: "indexed",
      title: "Verify your key pages are indexed",
      detail: "Run URL Inspection on your top 20 pages and remove any stray `noindex`.",
      impact: "high",
    },
    {
      id: "snippets",
      title: "Audit snippet controls",
      detail:
        "Search templates for `nosnippet`, low `max-snippet` values and `data-nosnippet`. Each one throttles what AI features can use.",
      impact: "high",
    },
    {
      id: "googlebot-cdn",
      title: "Allow Googlebot at the CDN and WAF, not just robots.txt",
      detail:
        'Make sure no "block AI bots" rule in Cloudflare or your WAF catches Googlebot. Verify with URL Inspection\'s live test.',
      impact: "high",
    },
    {
      id: "rendered-html",
      title: "Check the rendered HTML contains your main content",
      detail: "Use URL Inspection → View crawled page. Don't block JS or CSS resources.",
      impact: "high",
    },
    {
      id: "fan-out-map",
      title: "Map the fan-out for your top buyer questions",
      detail:
        "For each question, list the sub-questions Google is likely to search. Find the weakest one you could own outright.",
      impact: "high",
    },
    {
      id: "non-commodity",
      title: "Add first-hand, non-commodity material to key pages",
      detail:
        "Original data, tests, screenshots and named expertise — the things a generic answer can't supply.",
      impact: "high",
    },
    {
      id: "clusters",
      title: "Build depth as clusters, not per-variant pages",
      detail:
        "Cover subtopics in a comprehensive page or a linked cluster. Avoid thin pages per fan-out variant — that's scaled content abuse.",
      impact: "medium",
    },
    {
      id: "internal-links",
      title: "Strengthen internal links to deep pages",
      detail:
        "Link to your best subtopic pages from hubs and navigation; consolidate duplicates with canonicals.",
      impact: "medium",
    },
    {
      id: "media",
      title: "Publish original images and video",
      detail:
        "YouTube is the most-cited domain in AI Overviews. A short explainer video can earn a second citation path.",
      impact: "medium",
    },
    {
      id: "schema-match",
      title: "Keep structured data valid and matching the page",
      detail:
        "Not required for AI features, but mismatched markup undermines trust and rich results.",
      impact: "low",
    },
    {
      id: "merchant",
      title: "E-commerce: keep your Merchant Center feed complete",
      detail: "Prices, shipping, returns and attributes feed shopping answers in AI Mode.",
      impact: "medium",
    },
    {
      id: "gbp",
      title: "Local: keep your Google Business Profile current",
      detail: "Hours, categories, photos and reviews feed local answers and agentic booking.",
      impact: "medium",
    },
    {
      id: "measure",
      title: "Set up measurement",
      detail:
        "Review the Generative AI report monthly, compare those pages in GA4, run a weekly prompt panel, and annotate core updates.",
      impact: "high",
    },
  ],

  faqs: [
    {
      q: "How do I get my website into Google AI Overviews?",
      a: "Make sure the page is indexed, allowed a snippet, and that your site is set to Include in Search Console's Search generative AI setting. Beyond that it's SEO: Google grounds answers in its core ranking systems and fans the query out into subtopics, so helpful, first-hand content that wins those subtopics gets cited.",
    },
    {
      q: "Do I need schema markup or llms.txt for AI Overviews?",
      a: "No. Google says there is no special schema for AI features and it ignores llms.txt. Structured data still earns rich results, and it must match the visible text on the page.",
    },
    {
      q: "Can I opt out of AI Overviews without leaving Google Search?",
      a: "Yes. Since 31 August 2026, Search Console → Settings → Search generative AI can exclude a property from AI Overviews, AI Mode and Discover's AI features without affecting regular ranking. `nosnippet` also works, but removes your snippets everywhere.",
    },
    {
      q: "Does blocking Google-Extended remove me from AI Overviews?",
      a: "No. `Google-Extended` controls Gemini model training and grounding in the Gemini app and Vertex AI. Google states it does not affect inclusion in Google Search.",
    },
    {
      q: "How do I track AI Overviews traffic?",
      a: "Search Console's Generative AI report shows impressions by page, country and device, but no clicks. Clicks are blended into the Web performance report and into GA4's Organic Search, so pair the report with a citation tracker.",
    },
    {
      q: "Do I need to rank #1 to be cited in AI Overviews?",
      a: "No. Ahrefs' March 2026 study found only 37.9% of cited pages ranked in the top 10 for the query, because fan-out pulls sources from related sub-queries. Ranking well is still the strongest lever you control.",
    },
    {
      q: "Is AI Mode different from AI Overviews for SEO?",
      a: "The eligibility rules, controls and reporting are shared. But they cite the same URL only 13.7% of the time (Ahrefs), AI Mode answers are longer and show more domains, and AI Mode follow-ups count as new queries in Search Console.",
    },
    {
      q: "Do AI Overviews reduce clicks to my site?",
      a: "For uncited pages, usually yes: Pew measured an 8% click rate with a summary against 15% without, and Ahrefs a 58% drop for position one. Seer found cited brands get about 120% more clicks per impression than uncited ones.",
    },
  ],

  sources: [
    {
      title: "Optimizing your website for generative AI features",
      publisher: "Google Search Central",
      href: "https://developers.google.com/search/docs/fundamentals/ai-optimization-guide",
    },
    {
      title: "AI features and your website",
      publisher: "Google Search Central",
      href: "https://developers.google.com/search/docs/appearance/ai-features",
    },
    {
      title: "Introducing Search generative AI performance reports",
      publisher: "Google Search Central Blog",
      href: "https://developers.google.com/search/blog/2026/06/gen-ai-performance-reports",
    },
    {
      title: "Search generative AI control",
      publisher: "Search Console Help",
      href: "https://support.google.com/webmasters/answer/16908024",
    },
    {
      title: "Generative AI performance report",
      publisher: "Search Console Help",
      href: "https://support.google.com/webmasters/answer/16984139",
    },
    {
      title: "New controls for website owners",
      publisher: "Google",
      href: "https://blog.google/products-and-platforms/products/search/new-controls-website-owners/",
    },
    {
      title: "Robots meta tag, data-nosnippet and X-Robots-Tag specifications",
      publisher: "Google Search Central",
      href: "https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag",
    },
    {
      title: "Google's common crawlers (Google-Extended)",
      publisher: "Google Crawling Infrastructure",
      href: "https://developers.google.com/crawling/docs/crawlers-fetchers/google-common-crawlers",
    },
    {
      title: "How Search Console counts position, clicks and impressions",
      publisher: "Search Console Help",
      href: "https://support.google.com/webmasters/answer/7042828",
    },
    {
      title: "New ways to explore the web in AI Mode and AI Overviews",
      publisher: "Google",
      href: "https://blog.google/products-and-platforms/products/search/explore-web-generative-ai-search/",
    },
    {
      title: "Gemini 3 in AI Overviews and follow-ups in AI Mode",
      publisher: "Google",
      href: "https://blog.google/products-and-platforms/products/search/ai-mode-ai-overviews-updates/",
    },
    {
      title: "Search at I/O 2026",
      publisher: "Google",
      href: "https://blog.google/products-and-platforms/products/search/search-io-2026/",
    },
    {
      title: "Sundar Pichai's I/O 2026 keynote",
      publisher: "Google",
      href: "https://blog.google/innovation-and-ai/sundar-pichai-io-2026/",
    },
    {
      title: "Alphabet Q2 2026 earnings remarks",
      publisher: "Alphabet",
      href: "https://blog.google/company-news/inside-google/message-ceo/alphabet-earnings-q2-2026/",
    },
    {
      title: "CMA secures fairer deal for publishers in Google Search",
      publisher: "UK Competition and Markets Authority",
      href: "https://www.gov.uk/government/news/cma-secures-fairer-deal-for-publishers-and-improves-google-search-services-in-uk",
    },
    {
      title: "Google users are less likely to click on links when an AI summary appears",
      publisher: "Pew Research Center",
      href: "https://www.pewresearch.org/short-reads/2025/07/22/google-users-are-less-likely-to-click-on-links-when-an-ai-summary-appears-in-the-results/",
    },
    {
      title: "AI Overviews reduce clicks by 58%",
      publisher: "Ahrefs",
      href: "https://ahrefs.com/blog/ai-overviews-reduce-clicks-update/",
    },
    {
      title: "How many AI Overview citations rank in the top 10?",
      publisher: "Ahrefs",
      href: "https://ahrefs.com/blog/ai-overview-citations-top-10/",
    },
    {
      title: "AI Overviews vs AI Mode",
      publisher: "Ahrefs",
      href: "https://ahrefs.com/blog/ai-overviews-vs-ai-mode/",
    },
    {
      title: "AIO impact on Google CTR: 2026 update",
      publisher: "Seer Interactive",
      href: "https://www.seerinteractive.com/insights/aio-impact-on-google-ctr-2026-update",
    },
    {
      title: "Rank overlap after 16 months of AI Overviews",
      publisher: "BrightEdge",
      href: "https://www.brightedge.com/resources/weekly-ai-search-insights/rank-overlap-after-16-months-of-aio",
    },
  ],

  sameAs: [],

  furtherReading: [
    {
      title: "How to show up in Google AI Overviews: the 2026 playbook",
      href: "/blog/how-to-show-up-in-google-ai-overviews",
      description:
        "The step-by-step content playbook: mapping fan-out, writing liftable passages, and reading the AI report.",
    },
    {
      title: "Citation tracking",
      href: "/features/citation-tracking",
      description:
        "Track which prompts cite you in AI Overviews, AI Mode, ChatGPT, Perplexity and Gemini — weekly, automatically.",
    },
  ],
};
