/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardVisibilityRouteImport } from './routes/_authenticated/dashboard.visibility'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardKeywordsRouteImport } from './routes/_authenticated/dashboard.keywords'
import { Route as AuthenticatedDashboardIntegrationsRouteImport } from './routes/_authenticated/dashboard.integrations'
import { Route as AuthenticatedDashboardInsightsRouteImport } from './routes/_authenticated/dashboard.insights'
import { Route as AuthenticatedDashboardCalendarRouteImport } from './routes/_authenticated/dashboard.calendar'
import { Route as AuthenticatedDashboardBlogEngineRouteImport } from './routes/_authenticated/dashboard.blog-engine'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as ApiPublicV1PingRouteImport } from './routes/api/public/v1/ping'
import { Route as ApiPublicV1ArticlesRouteImport } from './routes/api/public/v1/articles'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksAutopilotRunRouteImport } from './routes/api/public/hooks/autopilot-run'
import { Route as AuthenticatedDashboardEditorBlogIdRouteImport } from './routes/_authenticated/dashboard.editor.$blogId'
import { Route as ApiPublicV1ArticlesIdRouteImport } from './routes/api/public/v1/articles.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardVisibilityRoute =
  AuthenticatedDashboardVisibilityRouteImport.update({
    id: '/visibility',
    path: '/visibility',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKeywordsRoute =
  AuthenticatedDashboardKeywordsRouteImport.update({
    id: '/keywords',
    path: '/keywords',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegrationsRoute =
  AuthenticatedDashboardIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInsightsRoute =
  AuthenticatedDashboardInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCalendarRoute =
  AuthenticatedDashboardCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBlogEngineRoute =
  AuthenticatedDashboardBlogEngineRouteImport.update({
    id: '/blog-engine',
    path: '/blog-engine',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicV1PingRoute = ApiPublicV1PingRouteImport.update({
  id: '/api/public/v1/ping',
  path: '/api/public/v1/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ArticlesRoute = ApiPublicV1ArticlesRouteImport.update({
  id: '/api/public/v1/articles',
  path: '/api/public/v1/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutopilotRunRoute =
  ApiPublicHooksAutopilotRunRouteImport.update({
    id: '/api/public/hooks/autopilot-run',
    path: '/api/public/hooks/autopilot-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardEditorBlogIdRoute =
  AuthenticatedDashboardEditorBlogIdRouteImport.update({
    id: '/editor/$blogId',
    path: '/editor/$blogId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicV1ArticlesIdRoute = ApiPublicV1ArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/features/$slug': typeof FeaturesSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/blog-engine': typeof AuthenticatedDashboardBlogEngineRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/insights': typeof AuthenticatedDashboardInsightsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/keywords': typeof AuthenticatedDashboardKeywordsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/visibility': typeof AuthenticatedDashboardVisibilityRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/editor/$blogId': typeof AuthenticatedDashboardEditorBlogIdRoute
  '/api/public/hooks/autopilot-run': typeof ApiPublicHooksAutopilotRunRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/articles': typeof ApiPublicV1ArticlesRouteWithChildren
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/articles/$id': typeof ApiPublicV1ArticlesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/features': typeof FeaturesIndexRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/blog-engine': typeof AuthenticatedDashboardBlogEngineRoute
  '/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/dashboard/insights': typeof AuthenticatedDashboardInsightsRoute
  '/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/dashboard/keywords': typeof AuthenticatedDashboardKeywordsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/visibility': typeof AuthenticatedDashboardVisibilityRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/editor/$blogId': typeof AuthenticatedDashboardEditorBlogIdRoute
  '/api/public/hooks/autopilot-run': typeof ApiPublicHooksAutopilotRunRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/articles': typeof ApiPublicV1ArticlesRouteWithChildren
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/articles/$id': typeof ApiPublicV1ArticlesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/features/$slug': typeof FeaturesSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/blog-engine': typeof AuthenticatedDashboardBlogEngineRoute
  '/_authenticated/dashboard/calendar': typeof AuthenticatedDashboardCalendarRoute
  '/_authenticated/dashboard/insights': typeof AuthenticatedDashboardInsightsRoute
  '/_authenticated/dashboard/integrations': typeof AuthenticatedDashboardIntegrationsRoute
  '/_authenticated/dashboard/keywords': typeof AuthenticatedDashboardKeywordsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/visibility': typeof AuthenticatedDashboardVisibilityRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/editor/$blogId': typeof AuthenticatedDashboardEditorBlogIdRoute
  '/api/public/hooks/autopilot-run': typeof ApiPublicHooksAutopilotRunRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/articles': typeof ApiPublicV1ArticlesRouteWithChildren
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/articles/$id': typeof ApiPublicV1ArticlesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/sitemap.xml'
    | '/dashboard'
    | '/features/$slug'
    | '/features/'
    | '/dashboard/billing'
    | '/dashboard/blog-engine'
    | '/dashboard/calendar'
    | '/dashboard/insights'
    | '/dashboard/integrations'
    | '/dashboard/keywords'
    | '/dashboard/settings'
    | '/dashboard/visibility'
    | '/dashboard/'
    | '/dashboard/editor/$blogId'
    | '/api/public/hooks/autopilot-run'
    | '/api/public/payments/webhook'
    | '/api/public/v1/articles'
    | '/api/public/v1/ping'
    | '/api/public/v1/articles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/sitemap.xml'
    | '/features/$slug'
    | '/features'
    | '/dashboard/billing'
    | '/dashboard/blog-engine'
    | '/dashboard/calendar'
    | '/dashboard/insights'
    | '/dashboard/integrations'
    | '/dashboard/keywords'
    | '/dashboard/settings'
    | '/dashboard/visibility'
    | '/dashboard'
    | '/dashboard/editor/$blogId'
    | '/api/public/hooks/autopilot-run'
    | '/api/public/payments/webhook'
    | '/api/public/v1/articles'
    | '/api/public/v1/ping'
    | '/api/public/v1/articles/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/legal'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/features/$slug'
    | '/features/'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/blog-engine'
    | '/_authenticated/dashboard/calendar'
    | '/_authenticated/dashboard/insights'
    | '/_authenticated/dashboard/integrations'
    | '/_authenticated/dashboard/keywords'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/visibility'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/editor/$blogId'
    | '/api/public/hooks/autopilot-run'
    | '/api/public/payments/webhook'
    | '/api/public/v1/articles'
    | '/api/public/v1/ping'
    | '/api/public/v1/articles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  ApiPublicHooksAutopilotRunRoute: typeof ApiPublicHooksAutopilotRunRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicV1ArticlesRoute: typeof ApiPublicV1ArticlesRouteWithChildren
  ApiPublicV1PingRoute: typeof ApiPublicV1PingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/visibility': {
      id: '/_authenticated/dashboard/visibility'
      path: '/visibility'
      fullPath: '/dashboard/visibility'
      preLoaderRoute: typeof AuthenticatedDashboardVisibilityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/keywords': {
      id: '/_authenticated/dashboard/keywords'
      path: '/keywords'
      fullPath: '/dashboard/keywords'
      preLoaderRoute: typeof AuthenticatedDashboardKeywordsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integrations': {
      id: '/_authenticated/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof AuthenticatedDashboardIntegrationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/insights': {
      id: '/_authenticated/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof AuthenticatedDashboardInsightsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/calendar': {
      id: '/_authenticated/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardCalendarRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/blog-engine': {
      id: '/_authenticated/dashboard/blog-engine'
      path: '/blog-engine'
      fullPath: '/dashboard/blog-engine'
      preLoaderRoute: typeof AuthenticatedDashboardBlogEngineRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/v1/ping': {
      id: '/api/public/v1/ping'
      path: '/api/public/v1/ping'
      fullPath: '/api/public/v1/ping'
      preLoaderRoute: typeof ApiPublicV1PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/articles': {
      id: '/api/public/v1/articles'
      path: '/api/public/v1/articles'
      fullPath: '/api/public/v1/articles'
      preLoaderRoute: typeof ApiPublicV1ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/autopilot-run': {
      id: '/api/public/hooks/autopilot-run'
      path: '/api/public/hooks/autopilot-run'
      fullPath: '/api/public/hooks/autopilot-run'
      preLoaderRoute: typeof ApiPublicHooksAutopilotRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/editor/$blogId': {
      id: '/_authenticated/dashboard/editor/$blogId'
      path: '/editor/$blogId'
      fullPath: '/dashboard/editor/$blogId'
      preLoaderRoute: typeof AuthenticatedDashboardEditorBlogIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/v1/articles/$id': {
      id: '/api/public/v1/articles/$id'
      path: '/$id'
      fullPath: '/api/public/v1/articles/$id'
      preLoaderRoute: typeof ApiPublicV1ArticlesIdRouteImport
      parentRoute: typeof ApiPublicV1ArticlesRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardBlogEngineRoute: typeof AuthenticatedDashboardBlogEngineRoute
  AuthenticatedDashboardCalendarRoute: typeof AuthenticatedDashboardCalendarRoute
  AuthenticatedDashboardInsightsRoute: typeof AuthenticatedDashboardInsightsRoute
  AuthenticatedDashboardIntegrationsRoute: typeof AuthenticatedDashboardIntegrationsRoute
  AuthenticatedDashboardKeywordsRoute: typeof AuthenticatedDashboardKeywordsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardVisibilityRoute: typeof AuthenticatedDashboardVisibilityRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardEditorBlogIdRoute: typeof AuthenticatedDashboardEditorBlogIdRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardBlogEngineRoute:
      AuthenticatedDashboardBlogEngineRoute,
    AuthenticatedDashboardCalendarRoute: AuthenticatedDashboardCalendarRoute,
    AuthenticatedDashboardInsightsRoute: AuthenticatedDashboardInsightsRoute,
    AuthenticatedDashboardIntegrationsRoute:
      AuthenticatedDashboardIntegrationsRoute,
    AuthenticatedDashboardKeywordsRoute: AuthenticatedDashboardKeywordsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardVisibilityRoute:
      AuthenticatedDashboardVisibilityRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardEditorBlogIdRoute:
      AuthenticatedDashboardEditorBlogIdRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1ArticlesRouteChildren {
  ApiPublicV1ArticlesIdRoute: typeof ApiPublicV1ArticlesIdRoute
}

const ApiPublicV1ArticlesRouteChildren: ApiPublicV1ArticlesRouteChildren = {
  ApiPublicV1ArticlesIdRoute: ApiPublicV1ArticlesIdRoute,
}

const ApiPublicV1ArticlesRouteWithChildren =
  ApiPublicV1ArticlesRoute._addFileChildren(ApiPublicV1ArticlesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  ApiPublicHooksAutopilotRunRoute: ApiPublicHooksAutopilotRunRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicV1ArticlesRoute: ApiPublicV1ArticlesRouteWithChildren,
  ApiPublicV1PingRoute: ApiPublicV1PingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
