// B4 (llms.txt adoption) and B2 (AI bot robots.txt census) from crawl.jsonl.
import { readFileSync, writeFileSync } from "node:fs";
import robotsParser from "robots-parser";
import { readJsonl } from "./jsonl.mjs";

const domains = new Map(JSON.parse(readFileSync("domains.json", "utf8")).map((d) => [d.host, d]));
const crawl = [];
for await (const r of readJsonl("crawl.jsonl")) {
  if (!domains.has(r.host)) continue;
  // keep only what the analysis reads, so memory stays small
  if (r.llmsFull?.text) r.llmsFull.text = r.llmsFull.text.slice(0, 2048);
  crawl.push(r);
}

const isHtml = (r) =>
  /text\/html|application\/xhtml/i.test(r.contentType ?? "") ||
  /^\s*(<!doctype|<html|<head|<body|<\?xml|<)/i.test(r.text ?? "");
const challenged = (r) =>
  !!r.cfMitigated ||
  /just a moment|cf-chl|challenge-platform|captcha|access denied|attention required|verify you are human|px-captcha|_Incapsula_|perimeterx|datadome/i.test(
    r.text ?? "",
  );

/** Catch-all or error responses that aren't an llms.txt at all (e.g. "OK", an IP, a 404 message, a GIF). */
function junk(r, body) {
  const ct = (r.contentType ?? "").toLowerCase();
  const startsMd = /^#/.test(body);
  if (ct && !/text|markdown/.test(ct) && !startsMd) return true;
  if (body.length < 20 && !startsMd) return true;
  if (
    body.length < 300 &&
    /page not found|not found|could not be found|route not found|system error/i.test(body)
  )
    return true;
  if (body.length < 300 && /^[\[{]/.test(body)) return true;
  return false;
}

function classifyFile(r, expectPath) {
  if (!r) return "unreachable";
  if (!r.ok) return r.error === "TimeoutError" ? "timeout" : "neterror";
  if (r.status === 200) {
    const body = (r.text ?? "").replace(/^﻿/, "").trim();
    if (!body) return "empty";
    if (isHtml(r)) return challenged(r) ? "blocked" : "html";
    if (junk(r, body)) return "junk";
    return "file";
  }
  if ([401, 403, 429, 503].includes(r.status))
    return challenged(r) || r.status !== 503 ? "blocked" : "error";
  if ([404, 410].includes(r.status)) return "none";
  if (r.status >= 500) return "error";
  return "other";
}

/* ---------------- B4: llms.txt ---------------- */

function stripFences(text) {
  return text.replace(/```[\s\S]*?```/g, "");
}

function lint(text) {
  const t = stripFences(text.replace(/^﻿/, ""));
  const lines = t.split(/\r?\n/);
  const nonEmpty = lines.filter((l) => l.trim());
  const first = nonEmpty[0] ?? "";
  const h1 = lines.filter((l) => /^#\s+\S/.test(l));
  const h2 = lines.filter((l) => /^##\s+\S/.test(l));
  const h3plus = lines.filter((l) => /^#{3,}\s+\S/.test(l));
  const links = [...t.matchAll(/\[([^\]]*)\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)].map((m) => m[2]);
  const listLinks = lines.filter((l) => /^\s*[-*+]\s*\[[^\]]+\]\([^)]+\)/.test(l));
  const bareUrls = [...t.matchAll(/(?<!\()https?:\/\/[^\s)>\]]+/g)].length;
  const head = text.slice(0, 4000);
  const gen = /generated by yoast seo/i.test(head)
    ? "Yoast SEO"
    : /generated by rank math/i.test(head)
      ? "Rank Math"
      : /generated by all in one seo/i.test(head)
        ? "All in One SEO"
        : /hostinger tools plugin/i.test(head)
          ? "Hostinger Tools"
          : /powered by Wix and supports the Model Context Protocol/i.test(head)
            ? "Wix"
            : /^#\s+Agent Instructions/m.test(head) &&
                /shop\.app\/SKILL\.md|Commerce Protocol/i.test(text)
              ? "Shopify agent template"
              : null;
  return {
    gen,
    h1First: /^#\s+\S/.test(first),
    h1Count: h1.length,
    blockquote: lines.some((l) => /^>\s*\S/.test(l)),
    h2Count: h2.length,
    h3plus: h3plus.length,
    links: links.length,
    listLinks: listLinks.length,
    relativeLinks: links.filter((u) => !/^(https?:|mailto:|#)/i.test(u)).length,
    mdLinks: links.filter((u) => /\.md(#.*)?$/i.test(u)).length,
    bareUrls,
    optional: lines.some((l) => /^##\s+optional\s*$/i.test(l)),
    robotsSyntax: /^\s*(user-agent|disallow|allow)\s*:/im.test(t),
    htmlTags: /<(div|p|br|a|span|script|meta|table|img)\b[^>]*>/i.test(t),
    noStructure: h1.length === 0 && h2.length === 0 && links.length === 0,
    firstLine: first.slice(0, 120),
    linkSample: links.filter((u) => /^https?:/i.test(u)).slice(0, 5),
  };
}

const segOf = (d) => {
  const s = [];
  if (d.segs.f500) s.push("f500", `f500:${d.segs.f500.sector}`);
  if (d.segs.saas) s.push("saas", `saas:${d.segs.saas.seg}`);
  if (d.segs.top10k) s.push("top10k", d.rank <= 1000 ? "top10k:1-1k" : "top10k:1k-10k");
  if (d.segs.news) s.push("news");
  if (d.segs.ecom) s.push("ecom");
  if (d.segs.news || d.segs.ecom) s.push("news+ecom");
  return s;
};

const hosts = [];
for (const r of crawl) {
  const d = domains.get(r.host);
  if (r.fatal) {
    hosts.push({ host: r.host, segs: segOf(d), reachable: false });
    continue;
  }
  const reachable = !!r.robots?.ok;
  const llms = classifyFile(r.llms);
  const full = classifyFile(r.llmsFull);
  const robotsState = classifyFile(r.robots);
  const h = {
    host: r.host,
    rank: d.rank,
    segs: segOf(d),
    reachable,
    llms,
    full,
    robotsState,
    llmsFinalUrl: r.llms?.finalUrl,
    llmsCT: r.llms?.contentType,
    llmsBytes: r.llms?.bytes,
    fullBytes: r.llmsFull?.bytes,
    fullCT: r.llmsFull?.contentType,
    server: r.robots?.server ?? r.llms?.server,
  };
  if (
    llms === "file" &&
    /currently listed for sale|domain name is for sale|this domain (name )?is for sale|buy this domain/i.test(
      r.llms.text.slice(0, 3000),
    )
  ) {
    h.parked = true;
  }
  if (llms === "file") {
    h.lint = lint(r.llms.text);
    h.llmsRedirectedAway =
      r.llms.finalUrl && !/\/llms\.txt$/i.test(new URL(r.llms.finalUrl).pathname);
  }
  if (full === "file") h.fullStart = (r.llmsFull.text ?? "").slice(0, 200);
  // B2 robots
  if (robotsState === "file") h.robots = r.robots.text;
  hosts.push(h);
}

/* ---------------- B2: robots.txt ---------------- */

export const BOTS = [
  ["GPTBot", "OpenAI", "training"],
  ["OAI-SearchBot", "OpenAI", "search"],
  ["ChatGPT-User", "OpenAI", "user"],
  ["ClaudeBot", "Anthropic", "training"],
  ["Claude-SearchBot", "Anthropic", "search"],
  ["Claude-User", "Anthropic", "user"],
  ["anthropic-ai", "Anthropic", "legacy"],
  ["PerplexityBot", "Perplexity", "search"],
  ["Perplexity-User", "Perplexity", "user"],
  ["Google-Extended", "Google", "training-token"],
  ["Applebot-Extended", "Apple", "training-token"],
  ["CCBot", "Common Crawl", "training"],
  ["Bytespider", "ByteDance", "training"],
  ["meta-externalagent", "Meta", "training"],
  ["Amazonbot", "Amazon", "mixed"],
  ["cohere-ai", "Cohere", "legacy"],
  ["Googlebot", "Google", "search-baseline"],
  ["Bingbot", "Microsoft", "search-baseline"],
];

function robotsFacts(host, text) {
  const url = `https://${host}/robots.txt`;
  const rp = robotsParser(url, text);
  const agents = [...text.matchAll(/^\s*user-agent\s*:\s*(.+?)\s*(#.*)?$/gim)].map((m) =>
    m[1].toLowerCase(),
  );
  const facts = {};
  for (const [bot] of BOTS) {
    const root = rp.isDisallowed(`https://${host}/`, bot);
    const deep = rp.isDisallowed(`https://${host}/rankbox-probe-page-7q`, bot);
    const named = agents.some((a) => a === bot.toLowerCase() || a.includes(bot.toLowerCase()));
    facts[bot] = { full: root && deep, partial: !(root && deep) && (root || deep), named };
  }
  const allBlocked =
    rp.isDisallowed(`https://${host}/`, "SomeRandomBot") &&
    rp.isDisallowed(`https://${host}/rankbox-probe-page-7q`, "SomeRandomBot");
  return {
    facts,
    wildcardFull: allBlocked,
    contentSignal: /^\s*content-signal\s*:/im.test(text),
    contentSignalLines: [...text.matchAll(/^\s*content-signal\s*:\s*(.+)$/gim)].map((m) =>
      m[1].trim().toLowerCase(),
    ),
    mentionsLlmsTxt: /llms\.txt/i.test(text),
    cfManaged: /BEGIN Cloudflare Managed content/i.test(text),
    sitemaps: (text.match(/^\s*sitemap\s*:/gim) ?? []).length,
    bytes: text.length,
  };
}

for (const h of hosts) {
  if (h.robots) {
    h.rb = robotsFacts(h.host, h.robots);
    delete h.robots;
  }
}

writeFileSync("hosts.json", JSON.stringify(hosts));

/* ---------------- summaries ---------------- */
const pct = (a, b) => (b ? +((100 * a) / b).toFixed(2) : null);
const SEGS = [
  "all",
  "f500",
  "saas",
  "saas:devtools",
  "saas:b2b-saas",
  "saas:software",
  "top10k",
  "top10k:1-1k",
  "top10k:1k-10k",
  "news",
  "ecom",
  "news+ecom",
];
const inSeg = (h, s) => !h.parked && (s === "all" || h.segs.includes(s));

const b4 = {};
for (const s of SEGS) {
  const H = hosts.filter((h) => inSeg(h, s));
  const R = H.filter((h) => h.reachable);
  const c = (k) => R.filter((h) => h.llms === k).length;
  const has = R.filter((h) => h.llms === "file");
  const fullHas = R.filter((h) => h.full === "file");
  b4[s] = {
    sample: H.length,
    reachable: R.length,
    llms: c("file"),
    llmsPct: pct(c("file"), R.length),
    full: fullHas.length,
    fullPct: pct(fullHas.length, R.length),
    either: R.filter((h) => h.llms === "file" || h.full === "file").length,
    html200: c("html"),
    blocked: c("blocked"),
    none: c("none"),
    other: R.length - c("file") - c("html") - c("blocked") - c("none"),
    h1First: has.filter((h) => h.lint.h1First).length,
  };
}
const f500Sectors = [...new Set(hosts.flatMap((h) => h.segs.filter((s) => s.startsWith("f500:"))))];
const bySector = {};
for (const s of f500Sectors) {
  const R = hosts.filter((h) => h.segs.includes(s) && h.reachable && !h.parked);
  bySector[s.slice(5)] = { n: R.length, llms: R.filter((h) => h.llms === "file").length };
}

const adopters = hosts.filter((h) => h.llms === "file" && !h.parked);
const L = adopters.map((h) => h.lint);
const lintSummary = {
  adopters: adopters.length,
  h1First: L.filter((l) => l.h1First).length,
  noH1: L.filter((l) => l.h1Count === 0).length,
  multiH1: L.filter((l) => l.h1Count > 1).length,
  blockquote: L.filter((l) => l.blockquote).length,
  h2: L.filter((l) => l.h2Count > 0).length,
  noLinks: L.filter((l) => l.links === 0).length,
  listLinks: L.filter((l) => l.listLinks > 0).length,
  relativeLinksFiles: L.filter((l) => l.relativeLinks > 0).length,
  mdLinksFiles: L.filter((l) => l.mdLinks > 0).length,
  bareUrlsOnly: L.filter((l) => l.links === 0 && l.bareUrls > 0).length,
  optional: L.filter((l) => l.optional).length,
  robotsSyntax: L.filter((l) => l.robotsSyntax).length,
  htmlTags: L.filter((l) => l.htmlTags).length,
  noStructure: L.filter((l) => l.noStructure).length,
  h3Only: L.filter((l) => l.h2Count === 0 && l.h3plus > 0).length,
  redirectedAway: adopters.filter((h) => h.llmsRedirectedAway).length,
  notTextCT: adopters.filter((h) => !/text\/(plain|markdown|x-markdown)/i.test(h.llmsCT ?? ""))
    .length,
  ctBreakdown: Object.entries(
    adopters.reduce(
      (a, h) => (
        (a[(h.llmsCT ?? "none").split(";")[0].trim().toLowerCase()] =
          (a[(h.llmsCT ?? "none").split(";")[0].trim().toLowerCase()] ?? 0) + 1),
        a
      ),
      {},
    ),
  ).sort((a, b) => b[1] - a[1]),
  bytesMedian: (() => {
    const b = adopters.map((h) => h.llmsBytes).sort((x, y) => x - y);
    return b[Math.floor(b.length / 2)];
  })(),
  bytesP90: (() => {
    const b = adopters.map((h) => h.llmsBytes).sort((x, y) => x - y);
    return b[Math.floor(b.length * 0.9)];
  })(),
  over100k: adopters.filter((h) => h.llmsBytes > 100 * 1024).length,
  linksMedian: (() => {
    const b = L.map((l) => l.links).sort((x, y) => x - y);
    return b[Math.floor(b.length / 2)];
  })(),
  parked: hosts.filter((h) => h.parked).length,
  generators: Object.entries(
    adopters.reduce(
      (a, h) => ((a[h.lint.gen ?? "none"] = (a[h.lint.gen ?? "none"] ?? 0) + 1), a),
      {},
    ),
  ).sort((a, b) => b[1] - a[1]),
  fullWithoutLlms: hosts.filter((h) => h.full === "file" && h.llms !== "file").length,
  fullAndLlms: hosts.filter((h) => h.full === "file" && h.llms === "file").length,
};

const b2 = {};
for (const s of SEGS) {
  const R = hosts.filter((h) => inSeg(h, s) && h.reachable);
  const parsed = R.filter((h) => h.rb);
  const row = {
    reachable: R.length,
    robotsFile: parsed.length,
    robotsNone: R.filter((h) => h.robotsState === "none").length,
    robotsBlocked: R.filter((h) => h.robotsState === "blocked").length,
    robotsHtml: R.filter((h) => h.robotsState === "html").length,
    wildcardFull: parsed.filter((h) => h.rb.wildcardFull).length,
    contentSignal: parsed.filter((h) => h.rb.contentSignal).length,
    cfManaged: parsed.filter((h) => h.rb.cfManaged).length,
    mentionsLlmsTxt: parsed.filter((h) => h.rb.mentionsLlmsTxt).length,
    bots: {},
  };
  for (const [bot] of BOTS) {
    row.bots[bot] = {
      full: parsed.filter((h) => h.rb.facts[bot].full).length,
      fullPct: pct(parsed.filter((h) => h.rb.facts[bot].full).length, parsed.length),
      fullNamed: parsed.filter((h) => h.rb.facts[bot].full && h.rb.facts[bot].named).length,
      partial: parsed.filter((h) => h.rb.facts[bot].partial).length,
      named: parsed.filter((h) => h.rb.facts[bot].named).length,
    };
  }
  // split policies
  const f = (h, b) => h.rb.facts[b].full;
  row.splits = {
    gptNotSearch: parsed.filter((h) => f(h, "GPTBot") && !f(h, "OAI-SearchBot")).length,
    gptAndSearch: parsed.filter((h) => f(h, "GPTBot") && f(h, "OAI-SearchBot")).length,
    searchNotGpt: parsed.filter((h) => !f(h, "GPTBot") && f(h, "OAI-SearchBot")).length,
    claudeNotSearch: parsed.filter((h) => f(h, "ClaudeBot") && !f(h, "Claude-SearchBot")).length,
    anyAI: parsed.filter((h) =>
      BOTS.filter(([, , t]) => t !== "search-baseline").some(([b]) => f(h, b)),
    ).length,
    anyAINamed: parsed.filter((h) =>
      BOTS.filter(([, , t]) => t !== "search-baseline").some(
        ([b]) => f(h, b) && h.rb.facts[b].named,
      ),
    ).length,
    blocksGoogleExtNotGooglebot: parsed.filter((h) => f(h, "Google-Extended") && !f(h, "Googlebot"))
      .length,
  };
  b2[s] = row;
}
const csLines = {};
for (const h of hosts)
  for (const l of h.rb?.contentSignalLines ?? []) csLines[l] = (csLines[l] ?? 0) + 1;

writeFileSync(
  "crawl-summary.json",
  JSON.stringify(
    {
      crawled: hosts.length,
      b4,
      bySector,
      lintSummary,
      b2,
      contentSignalLines: Object.entries(csLines)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 15),
    },
    null,
    1,
  ),
);
console.log("crawled", hosts.length);
for (const s of SEGS) console.log(s.padEnd(16), JSON.stringify(b4[s]));
console.log(JSON.stringify(lintSummary));
for (const s of ["all", "news+ecom", "news", "ecom", "f500", "top10k", "saas"])
  console.log(
    s.padEnd(10),
    "parsed",
    b2[s].robotsFile,
    Object.entries(b2[s].bots)
      .map(([b, v]) => `${b}:${v.fullPct}`)
      .join(" "),
    "| splits",
    JSON.stringify(b2[s].splits),
    "| cs",
    b2[s].contentSignal,
    "cf",
    b2[s].cfManaged,
    "wild",
    b2[s].wildcardFull,
  );
